export type RepositoryData = {
  id: string;
  githubId: string;
  name: string;
  fullName: string;
  owner: string;
  description: string;
  emoji: string;
  faIcon: string;
  defaultBranch: string;
  docsPath: string;
  pages: number;
  lastSync: string;
  syncing: boolean;
  published: boolean;
  featured: boolean;
  status: "active" | "syncing";
  language: string;
  topics: string[];
  homepage: string;
  stargazersCount: number;
  forksCount: number;
  updatedAt: Date;
  syncedAt: Date;
  latestTag: string;
  baseSlug: string;
};
