packages:
  - apps/*
  - packages/*

onlyBuiltDependencies:
  - '@clerk/shared'
  - '@prisma/client'
  - '@prisma/engines'
  - esbuild
  - prisma
  - sharp
  - unrs-resolver

overrides:
  hono@<4.10.3: '>=4.10.3'
  hono@<4.9.7: '>=4.9.7'
  hono@>=1.1.0 <4.10.2: '>=4.10.2'
  mdast-util-to-hast@>=13.0.0 <13.2.1: '>=13.2.1'
  next@>=16.0.0-beta.0 <16.0.9: '>=16.0.9'
  next@>=16.0.0-canary.0 <16.0.7: '>=16.0.7'
  valibot@>=0.31.0 <1.2.0: '>=1.2.0'
