
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * WARNING: This is an internal file that is subject to change!
 *
 * 🛑 Under no circumstances should you import this file directly! 🛑
 *
 * All exports from this file are wrapped under a `Prisma` namespace object in the client.ts file.
 * While this enables partial backward compatibility, it is not part of the stable public API.
 *
 * If you are looking for your Models, Enums, and Input Types, please import them from the respective
 * model files in the `model` directory!
 */

import * as runtime from "@prisma/client/runtime/client"
import type * as Prisma from "../models"
import { type PrismaClient } from "./class"

export type * from '../models'

export type DMMF = typeof runtime.DMMF

export type PrismaPromise<T> = runtime.Types.Public.PrismaPromise<T>

/**
 * Prisma Errors
 */

export const PrismaClientKnownRequestError = runtime.PrismaClientKnownRequestError
export type PrismaClientKnownRequestError = runtime.PrismaClientKnownRequestError

export const PrismaClientUnknownRequestError = runtime.PrismaClientUnknownRequestError
export type PrismaClientUnknownRequestError = runtime.PrismaClientUnknownRequestError

export const PrismaClientRustPanicError = runtime.PrismaClientRustPanicError
export type PrismaClientRustPanicError = runtime.PrismaClientRustPanicError

export const PrismaClientInitializationError = runtime.PrismaClientInitializationError
export type PrismaClientInitializationError = runtime.PrismaClientInitializationError

export const PrismaClientValidationError = runtime.PrismaClientValidationError
export type PrismaClientValidationError = runtime.PrismaClientValidationError

/**
 * Re-export of sql-template-tag
 */
export const sql = runtime.sqltag
export const empty = runtime.empty
export const join = runtime.join
export const raw = runtime.raw
export const Sql = runtime.Sql
export type Sql = runtime.Sql



/**
 * Decimal.js
 */
export const Decimal = runtime.Decimal
export type Decimal = runtime.Decimal

export type DecimalJsLike = runtime.DecimalJsLike

/**
* Extensions
*/
export type Extension = runtime.Types.Extensions.UserArgs
export const getExtensionContext = runtime.Extensions.getExtensionContext
export type Args<T, F extends runtime.Operation> = runtime.Types.Public.Args<T, F>
export type Payload<T, F extends runtime.Operation = never> = runtime.Types.Public.Payload<T, F>
export type Result<T, A, F extends runtime.Operation> = runtime.Types.Public.Result<T, A, F>
export type Exact<A, W> = runtime.Types.Public.Exact<A, W>

export type PrismaVersion = {
  client: string
  engine: string
}

/**
 * Prisma Client JS version: 7.0.0
 * Query Engine version: 0c19ccc313cf9911a90d99d2ac2eb0280c76c513
 */
export const prismaVersion: PrismaVersion = {
  client: "7.0.0",
  engine: "0c19ccc313cf9911a90d99d2ac2eb0280c76c513"
}

/**
 * Utility Types
 */

export type Bytes = runtime.Bytes
export type JsonObject = runtime.JsonObject
export type JsonArray = runtime.JsonArray
export type JsonValue = runtime.JsonValue
export type InputJsonObject = runtime.InputJsonObject
export type InputJsonArray = runtime.InputJsonArray
export type InputJsonValue = runtime.InputJsonValue


export const NullTypes = {
  DbNull: runtime.NullTypes.DbNull as (new (secret: never) => typeof runtime.DbNull),
  JsonNull: runtime.NullTypes.JsonNull as (new (secret: never) => typeof runtime.JsonNull),
  AnyNull: runtime.NullTypes.AnyNull as (new (secret: never) => typeof runtime.AnyNull),
}
/**
 * Helper for filtering JSON entries that have `null` on the database (empty on the db)
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const DbNull = runtime.DbNull

/**
 * Helper for filtering JSON entries that have JSON `null` values (not empty on the db)
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const JsonNull = runtime.JsonNull

/**
 * Helper for filtering JSON entries that are `Prisma.DbNull` or `Prisma.JsonNull`
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const AnyNull = runtime.AnyNull


type SelectAndInclude = {
  select: any
  include: any
}

type SelectAndOmit = {
  select: any
  omit: any
}

/**
 * From T, pick a set of properties whose keys are in the union K
 */
type Prisma__Pick<T, K extends keyof T> = {
    [P in K]: T[P];
};

export type Enumerable<T> = T | Array<T>;

/**
 * Subset
 * @desc From `T` pick properties that exist in `U`. Simple version of Intersection
 */
export type Subset<T, U> = {
  [key in keyof T]: key extends keyof U ? T[key] : never;
};

/**
 * SelectSubset
 * @desc From `T` pick properties that exist in `U`. Simple version of Intersection.
 * Additionally, it validates, if both select and include are present. If the case, it errors.
 */
export type SelectSubset<T, U> = {
  [key in keyof T]: key extends keyof U ? T[key] : never
} &
  (T extends SelectAndInclude
    ? 'Please either choose `select` or `include`.'
    : T extends SelectAndOmit
      ? 'Please either choose `select` or `omit`.'
      : {})

/**
 * Subset + Intersection
 * @desc From `T` pick properties that exist in `U` and intersect `K`
 */
export type SubsetIntersection<T, U, K> = {
  [key in keyof T]: key extends keyof U ? T[key] : never
} &
  K

type Without<T, U> = { [P in Exclude<keyof T, keyof U>]?: never };

/**
 * XOR is needed to have a real mutually exclusive union type
 * https://stackoverflow.com/questions/42123407/does-typescript-support-mutually-exclusive-types
 */
export type XOR<T, U> =
  T extends object ?
  U extends object ?
    (Without<T, U> & U) | (Without<U, T> & T)
  : U : T


/**
 * Is T a Record?
 */
type IsObject<T extends any> = T extends Array<any>
? False
: T extends Date
? False
: T extends Uint8Array
? False
: T extends BigInt
? False
: T extends object
? True
: False


/**
 * If it's T[], return T
 */
export type UnEnumerate<T extends unknown> = T extends Array<infer U> ? U : T

/**
 * From ts-toolbelt
 */

type __Either<O extends object, K extends Key> = Omit<O, K> &
  {
    // Merge all but K
    [P in K]: Prisma__Pick<O, P & keyof O> // With K possibilities
  }[K]

type EitherStrict<O extends object, K extends Key> = Strict<__Either<O, K>>

type EitherLoose<O extends object, K extends Key> = ComputeRaw<__Either<O, K>>

type _Either<
  O extends object,
  K extends Key,
  strict extends Boolean
> = {
  1: EitherStrict<O, K>
  0: EitherLoose<O, K>
}[strict]

export type Either<
  O extends object,
  K extends Key,
  strict extends Boolean = 1
> = O extends unknown ? _Either<O, K, strict> : never

export type Union = any

export type PatchUndefined<O extends object, O1 extends object> = {
  [K in keyof O]: O[K] extends undefined ? At<O1, K> : O[K]
} & {}

/** Helper Types for "Merge" **/
export type IntersectOf<U extends Union> = (
  U extends unknown ? (k: U) => void : never
) extends (k: infer I) => void
  ? I
  : never

export type Overwrite<O extends object, O1 extends object> = {
    [K in keyof O]: K extends keyof O1 ? O1[K] : O[K];
} & {};

type _Merge<U extends object> = IntersectOf<Overwrite<U, {
    [K in keyof U]-?: At<U, K>;
}>>;

type Key = string | number | symbol;
type AtStrict<O extends object, K extends Key> = O[K & keyof O];
type AtLoose<O extends object, K extends Key> = O extends unknown ? AtStrict<O, K> : never;
export type At<O extends object, K extends Key, strict extends Boolean = 1> = {
    1: AtStrict<O, K>;
    0: AtLoose<O, K>;
}[strict];

export type ComputeRaw<A extends any> = A extends Function ? A : {
  [K in keyof A]: A[K];
} & {};

export type OptionalFlat<O> = {
  [K in keyof O]?: O[K];
} & {};

type _Record<K extends keyof any, T> = {
  [P in K]: T;
};

// cause typescript not to expand types and preserve names
type NoExpand<T> = T extends unknown ? T : never;

// this type assumes the passed object is entirely optional
export type AtLeast<O extends object, K extends string> = NoExpand<
  O extends unknown
  ? | (K extends keyof O ? { [P in K]: O[P] } & O : O)
    | {[P in keyof O as P extends K ? P : never]-?: O[P]} & O
  : never>;

type _Strict<U, _U = U> = U extends unknown ? U & OptionalFlat<_Record<Exclude<Keys<_U>, keyof U>, never>> : never;

export type Strict<U extends object> = ComputeRaw<_Strict<U>>;
/** End Helper Types for "Merge" **/

export type Merge<U extends object> = ComputeRaw<_Merge<Strict<U>>>;

export type Boolean = True | False

export type True = 1

export type False = 0

export type Not<B extends Boolean> = {
  0: 1
  1: 0
}[B]

export type Extends<A1 extends any, A2 extends any> = [A1] extends [never]
  ? 0 // anything `never` is false
  : A1 extends A2
  ? 1
  : 0

export type Has<U extends Union, U1 extends Union> = Not<
  Extends<Exclude<U1, U>, U1>
>

export type Or<B1 extends Boolean, B2 extends Boolean> = {
  0: {
    0: 0
    1: 1
  }
  1: {
    0: 1
    1: 1
  }
}[B1][B2]

export type Keys<U extends Union> = U extends unknown ? keyof U : never

export type GetScalarType<T, O> = O extends object ? {
  [P in keyof T]: P extends keyof O
    ? O[P]
    : never
} : never

type FieldPaths<
  T,
  U = Omit<T, '_avg' | '_sum' | '_count' | '_min' | '_max'>
> = IsObject<T> extends True ? U : T

export type GetHavingFields<T> = {
  [K in keyof T]: Or<
    Or<Extends<'OR', K>, Extends<'AND', K>>,
    Extends<'NOT', K>
  > extends True
    ? // infer is only needed to not hit TS limit
      // based on the brilliant idea of Pierre-Antoine Mills
      // https://github.com/microsoft/TypeScript/issues/30188#issuecomment-478938437
      T[K] extends infer TK
      ? GetHavingFields<UnEnumerate<TK> extends object ? Merge<UnEnumerate<TK>> : never>
      : never
    : {} extends FieldPaths<T[K]>
    ? never
    : K
}[keyof T]

/**
 * Convert tuple to union
 */
type _TupleToUnion<T> = T extends (infer E)[] ? E : never
type TupleToUnion<K extends readonly any[]> = _TupleToUnion<K>
export type MaybeTupleToUnion<T> = T extends any[] ? TupleToUnion<T> : T

/**
 * Like `Pick`, but additionally can also accept an array of keys
 */
export type PickEnumerable<T, K extends Enumerable<keyof T> | keyof T> = Prisma__Pick<T, MaybeTupleToUnion<K>>

/**
 * Exclude all keys with underscores
 */
export type ExcludeUnderscoreKeys<T extends string> = T extends `_${string}` ? never : T


export type FieldRef<Model, FieldType> = runtime.FieldRef<Model, FieldType>

type FieldRefInputType<Model, FieldType> = Model extends never ? never : FieldRef<Model, FieldType>


export const ModelName = {
  Repository: 'Repository',
  Issue: 'Issue',
  PullRequest: 'PullRequest',
  Commit: 'Commit',
  Release: 'Release',
  VersionTag: 'VersionTag',
  Contributor: 'Contributor',
  ContributorContribution: 'ContributorContribution',
  DocumentationContent: 'DocumentationContent',
  DocumentationMetadata: 'DocumentationMetadata',
  SyncLog: 'SyncLog',
  Settings: 'Settings',
  Project: 'Project',
  ProjectSource: 'ProjectSource',
  Version: 'Version',
  Content: 'Content',
  NavStructure: 'NavStructure'
} as const

export type ModelName = (typeof ModelName)[keyof typeof ModelName]



export interface TypeMapCb<GlobalOmitOptions = {}> extends runtime.Types.Utils.Fn<{extArgs: runtime.Types.Extensions.InternalArgs }, runtime.Types.Utils.Record<string, any>> {
  returns: TypeMap<this['params']['extArgs'], GlobalOmitOptions>
}

export type TypeMap<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> = {
  globalOmitOptions: {
    omit: GlobalOmitOptions
  }
  meta: {
    modelProps: "repository" | "issue" | "pullRequest" | "commit" | "release" | "versionTag" | "contributor" | "contributorContribution" | "documentationContent" | "documentationMetadata" | "syncLog" | "settings" | "project" | "projectSource" | "version" | "content" | "navStructure"
    txIsolationLevel: TransactionIsolationLevel
  }
  model: {
    Repository: {
      payload: Prisma.$RepositoryPayload<ExtArgs>
      fields: Prisma.RepositoryFieldRefs
      operations: {
        findUnique: {
          args: Prisma.RepositoryFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$RepositoryPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.RepositoryFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$RepositoryPayload>
        }
        findFirst: {
          args: Prisma.RepositoryFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$RepositoryPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.RepositoryFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$RepositoryPayload>
        }
        findMany: {
          args: Prisma.RepositoryFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$RepositoryPayload>[]
        }
        create: {
          args: Prisma.RepositoryCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$RepositoryPayload>
        }
        createMany: {
          args: Prisma.RepositoryCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.RepositoryCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$RepositoryPayload>[]
        }
        delete: {
          args: Prisma.RepositoryDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$RepositoryPayload>
        }
        update: {
          args: Prisma.RepositoryUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$RepositoryPayload>
        }
        deleteMany: {
          args: Prisma.RepositoryDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.RepositoryUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.RepositoryUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$RepositoryPayload>[]
        }
        upsert: {
          args: Prisma.RepositoryUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$RepositoryPayload>
        }
        aggregate: {
          args: Prisma.RepositoryAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateRepository>
        }
        groupBy: {
          args: Prisma.RepositoryGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.RepositoryGroupByOutputType>[]
        }
        count: {
          args: Prisma.RepositoryCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.RepositoryCountAggregateOutputType> | number
        }
      }
    }
    Issue: {
      payload: Prisma.$IssuePayload<ExtArgs>
      fields: Prisma.IssueFieldRefs
      operations: {
        findUnique: {
          args: Prisma.IssueFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$IssuePayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.IssueFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$IssuePayload>
        }
        findFirst: {
          args: Prisma.IssueFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$IssuePayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.IssueFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$IssuePayload>
        }
        findMany: {
          args: Prisma.IssueFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$IssuePayload>[]
        }
        create: {
          args: Prisma.IssueCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$IssuePayload>
        }
        createMany: {
          args: Prisma.IssueCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.IssueCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$IssuePayload>[]
        }
        delete: {
          args: Prisma.IssueDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$IssuePayload>
        }
        update: {
          args: Prisma.IssueUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$IssuePayload>
        }
        deleteMany: {
          args: Prisma.IssueDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.IssueUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.IssueUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$IssuePayload>[]
        }
        upsert: {
          args: Prisma.IssueUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$IssuePayload>
        }
        aggregate: {
          args: Prisma.IssueAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateIssue>
        }
        groupBy: {
          args: Prisma.IssueGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.IssueGroupByOutputType>[]
        }
        count: {
          args: Prisma.IssueCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.IssueCountAggregateOutputType> | number
        }
      }
    }
    PullRequest: {
      payload: Prisma.$PullRequestPayload<ExtArgs>
      fields: Prisma.PullRequestFieldRefs
      operations: {
        findUnique: {
          args: Prisma.PullRequestFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$PullRequestPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.PullRequestFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$PullRequestPayload>
        }
        findFirst: {
          args: Prisma.PullRequestFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$PullRequestPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.PullRequestFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$PullRequestPayload>
        }
        findMany: {
          args: Prisma.PullRequestFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$PullRequestPayload>[]
        }
        create: {
          args: Prisma.PullRequestCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$PullRequestPayload>
        }
        createMany: {
          args: Prisma.PullRequestCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.PullRequestCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$PullRequestPayload>[]
        }
        delete: {
          args: Prisma.PullRequestDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$PullRequestPayload>
        }
        update: {
          args: Prisma.PullRequestUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$PullRequestPayload>
        }
        deleteMany: {
          args: Prisma.PullRequestDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.PullRequestUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.PullRequestUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$PullRequestPayload>[]
        }
        upsert: {
          args: Prisma.PullRequestUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$PullRequestPayload>
        }
        aggregate: {
          args: Prisma.PullRequestAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregatePullRequest>
        }
        groupBy: {
          args: Prisma.PullRequestGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.PullRequestGroupByOutputType>[]
        }
        count: {
          args: Prisma.PullRequestCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.PullRequestCountAggregateOutputType> | number
        }
      }
    }
    Commit: {
      payload: Prisma.$CommitPayload<ExtArgs>
      fields: Prisma.CommitFieldRefs
      operations: {
        findUnique: {
          args: Prisma.CommitFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$CommitPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.CommitFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$CommitPayload>
        }
        findFirst: {
          args: Prisma.CommitFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$CommitPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.CommitFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$CommitPayload>
        }
        findMany: {
          args: Prisma.CommitFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$CommitPayload>[]
        }
        create: {
          args: Prisma.CommitCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$CommitPayload>
        }
        createMany: {
          args: Prisma.CommitCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.CommitCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$CommitPayload>[]
        }
        delete: {
          args: Prisma.CommitDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$CommitPayload>
        }
        update: {
          args: Prisma.CommitUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$CommitPayload>
        }
        deleteMany: {
          args: Prisma.CommitDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.CommitUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.CommitUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$CommitPayload>[]
        }
        upsert: {
          args: Prisma.CommitUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$CommitPayload>
        }
        aggregate: {
          args: Prisma.CommitAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateCommit>
        }
        groupBy: {
          args: Prisma.CommitGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.CommitGroupByOutputType>[]
        }
        count: {
          args: Prisma.CommitCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.CommitCountAggregateOutputType> | number
        }
      }
    }
    Release: {
      payload: Prisma.$ReleasePayload<ExtArgs>
      fields: Prisma.ReleaseFieldRefs
      operations: {
        findUnique: {
          args: Prisma.ReleaseFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ReleasePayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.ReleaseFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ReleasePayload>
        }
        findFirst: {
          args: Prisma.ReleaseFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ReleasePayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.ReleaseFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ReleasePayload>
        }
        findMany: {
          args: Prisma.ReleaseFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ReleasePayload>[]
        }
        create: {
          args: Prisma.ReleaseCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ReleasePayload>
        }
        createMany: {
          args: Prisma.ReleaseCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.ReleaseCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ReleasePayload>[]
        }
        delete: {
          args: Prisma.ReleaseDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ReleasePayload>
        }
        update: {
          args: Prisma.ReleaseUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ReleasePayload>
        }
        deleteMany: {
          args: Prisma.ReleaseDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.ReleaseUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.ReleaseUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ReleasePayload>[]
        }
        upsert: {
          args: Prisma.ReleaseUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ReleasePayload>
        }
        aggregate: {
          args: Prisma.ReleaseAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateRelease>
        }
        groupBy: {
          args: Prisma.ReleaseGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.ReleaseGroupByOutputType>[]
        }
        count: {
          args: Prisma.ReleaseCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.ReleaseCountAggregateOutputType> | number
        }
      }
    }
    VersionTag: {
      payload: Prisma.$VersionTagPayload<ExtArgs>
      fields: Prisma.VersionTagFieldRefs
      operations: {
        findUnique: {
          args: Prisma.VersionTagFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$VersionTagPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.VersionTagFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$VersionTagPayload>
        }
        findFirst: {
          args: Prisma.VersionTagFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$VersionTagPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.VersionTagFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$VersionTagPayload>
        }
        findMany: {
          args: Prisma.VersionTagFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$VersionTagPayload>[]
        }
        create: {
          args: Prisma.VersionTagCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$VersionTagPayload>
        }
        createMany: {
          args: Prisma.VersionTagCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.VersionTagCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$VersionTagPayload>[]
        }
        delete: {
          args: Prisma.VersionTagDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$VersionTagPayload>
        }
        update: {
          args: Prisma.VersionTagUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$VersionTagPayload>
        }
        deleteMany: {
          args: Prisma.VersionTagDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.VersionTagUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.VersionTagUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$VersionTagPayload>[]
        }
        upsert: {
          args: Prisma.VersionTagUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$VersionTagPayload>
        }
        aggregate: {
          args: Prisma.VersionTagAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateVersionTag>
        }
        groupBy: {
          args: Prisma.VersionTagGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.VersionTagGroupByOutputType>[]
        }
        count: {
          args: Prisma.VersionTagCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.VersionTagCountAggregateOutputType> | number
        }
      }
    }
    Contributor: {
      payload: Prisma.$ContributorPayload<ExtArgs>
      fields: Prisma.ContributorFieldRefs
      operations: {
        findUnique: {
          args: Prisma.ContributorFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ContributorPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.ContributorFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ContributorPayload>
        }
        findFirst: {
          args: Prisma.ContributorFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ContributorPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.ContributorFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ContributorPayload>
        }
        findMany: {
          args: Prisma.ContributorFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ContributorPayload>[]
        }
        create: {
          args: Prisma.ContributorCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ContributorPayload>
        }
        createMany: {
          args: Prisma.ContributorCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.ContributorCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ContributorPayload>[]
        }
        delete: {
          args: Prisma.ContributorDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ContributorPayload>
        }
        update: {
          args: Prisma.ContributorUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ContributorPayload>
        }
        deleteMany: {
          args: Prisma.ContributorDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.ContributorUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.ContributorUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ContributorPayload>[]
        }
        upsert: {
          args: Prisma.ContributorUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ContributorPayload>
        }
        aggregate: {
          args: Prisma.ContributorAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateContributor>
        }
        groupBy: {
          args: Prisma.ContributorGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.ContributorGroupByOutputType>[]
        }
        count: {
          args: Prisma.ContributorCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.ContributorCountAggregateOutputType> | number
        }
      }
    }
    ContributorContribution: {
      payload: Prisma.$ContributorContributionPayload<ExtArgs>
      fields: Prisma.ContributorContributionFieldRefs
      operations: {
        findUnique: {
          args: Prisma.ContributorContributionFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ContributorContributionPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.ContributorContributionFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ContributorContributionPayload>
        }
        findFirst: {
          args: Prisma.ContributorContributionFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ContributorContributionPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.ContributorContributionFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ContributorContributionPayload>
        }
        findMany: {
          args: Prisma.ContributorContributionFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ContributorContributionPayload>[]
        }
        create: {
          args: Prisma.ContributorContributionCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ContributorContributionPayload>
        }
        createMany: {
          args: Prisma.ContributorContributionCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.ContributorContributionCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ContributorContributionPayload>[]
        }
        delete: {
          args: Prisma.ContributorContributionDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ContributorContributionPayload>
        }
        update: {
          args: Prisma.ContributorContributionUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ContributorContributionPayload>
        }
        deleteMany: {
          args: Prisma.ContributorContributionDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.ContributorContributionUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.ContributorContributionUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ContributorContributionPayload>[]
        }
        upsert: {
          args: Prisma.ContributorContributionUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ContributorContributionPayload>
        }
        aggregate: {
          args: Prisma.ContributorContributionAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateContributorContribution>
        }
        groupBy: {
          args: Prisma.ContributorContributionGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.ContributorContributionGroupByOutputType>[]
        }
        count: {
          args: Prisma.ContributorContributionCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.ContributorContributionCountAggregateOutputType> | number
        }
      }
    }
    DocumentationContent: {
      payload: Prisma.$DocumentationContentPayload<ExtArgs>
      fields: Prisma.DocumentationContentFieldRefs
      operations: {
        findUnique: {
          args: Prisma.DocumentationContentFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$DocumentationContentPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.DocumentationContentFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$DocumentationContentPayload>
        }
        findFirst: {
          args: Prisma.DocumentationContentFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$DocumentationContentPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.DocumentationContentFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$DocumentationContentPayload>
        }
        findMany: {
          args: Prisma.DocumentationContentFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$DocumentationContentPayload>[]
        }
        create: {
          args: Prisma.DocumentationContentCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$DocumentationContentPayload>
        }
        createMany: {
          args: Prisma.DocumentationContentCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.DocumentationContentCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$DocumentationContentPayload>[]
        }
        delete: {
          args: Prisma.DocumentationContentDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$DocumentationContentPayload>
        }
        update: {
          args: Prisma.DocumentationContentUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$DocumentationContentPayload>
        }
        deleteMany: {
          args: Prisma.DocumentationContentDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.DocumentationContentUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.DocumentationContentUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$DocumentationContentPayload>[]
        }
        upsert: {
          args: Prisma.DocumentationContentUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$DocumentationContentPayload>
        }
        aggregate: {
          args: Prisma.DocumentationContentAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateDocumentationContent>
        }
        groupBy: {
          args: Prisma.DocumentationContentGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.DocumentationContentGroupByOutputType>[]
        }
        count: {
          args: Prisma.DocumentationContentCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.DocumentationContentCountAggregateOutputType> | number
        }
      }
    }
    DocumentationMetadata: {
      payload: Prisma.$DocumentationMetadataPayload<ExtArgs>
      fields: Prisma.DocumentationMetadataFieldRefs
      operations: {
        findUnique: {
          args: Prisma.DocumentationMetadataFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$DocumentationMetadataPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.DocumentationMetadataFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$DocumentationMetadataPayload>
        }
        findFirst: {
          args: Prisma.DocumentationMetadataFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$DocumentationMetadataPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.DocumentationMetadataFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$DocumentationMetadataPayload>
        }
        findMany: {
          args: Prisma.DocumentationMetadataFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$DocumentationMetadataPayload>[]
        }
        create: {
          args: Prisma.DocumentationMetadataCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$DocumentationMetadataPayload>
        }
        createMany: {
          args: Prisma.DocumentationMetadataCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.DocumentationMetadataCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$DocumentationMetadataPayload>[]
        }
        delete: {
          args: Prisma.DocumentationMetadataDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$DocumentationMetadataPayload>
        }
        update: {
          args: Prisma.DocumentationMetadataUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$DocumentationMetadataPayload>
        }
        deleteMany: {
          args: Prisma.DocumentationMetadataDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.DocumentationMetadataUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.DocumentationMetadataUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$DocumentationMetadataPayload>[]
        }
        upsert: {
          args: Prisma.DocumentationMetadataUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$DocumentationMetadataPayload>
        }
        aggregate: {
          args: Prisma.DocumentationMetadataAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateDocumentationMetadata>
        }
        groupBy: {
          args: Prisma.DocumentationMetadataGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.DocumentationMetadataGroupByOutputType>[]
        }
        count: {
          args: Prisma.DocumentationMetadataCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.DocumentationMetadataCountAggregateOutputType> | number
        }
      }
    }
    SyncLog: {
      payload: Prisma.$SyncLogPayload<ExtArgs>
      fields: Prisma.SyncLogFieldRefs
      operations: {
        findUnique: {
          args: Prisma.SyncLogFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$SyncLogPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.SyncLogFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$SyncLogPayload>
        }
        findFirst: {
          args: Prisma.SyncLogFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$SyncLogPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.SyncLogFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$SyncLogPayload>
        }
        findMany: {
          args: Prisma.SyncLogFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$SyncLogPayload>[]
        }
        create: {
          args: Prisma.SyncLogCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$SyncLogPayload>
        }
        createMany: {
          args: Prisma.SyncLogCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.SyncLogCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$SyncLogPayload>[]
        }
        delete: {
          args: Prisma.SyncLogDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$SyncLogPayload>
        }
        update: {
          args: Prisma.SyncLogUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$SyncLogPayload>
        }
        deleteMany: {
          args: Prisma.SyncLogDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.SyncLogUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.SyncLogUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$SyncLogPayload>[]
        }
        upsert: {
          args: Prisma.SyncLogUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$SyncLogPayload>
        }
        aggregate: {
          args: Prisma.SyncLogAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateSyncLog>
        }
        groupBy: {
          args: Prisma.SyncLogGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.SyncLogGroupByOutputType>[]
        }
        count: {
          args: Prisma.SyncLogCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.SyncLogCountAggregateOutputType> | number
        }
      }
    }
    Settings: {
      payload: Prisma.$SettingsPayload<ExtArgs>
      fields: Prisma.SettingsFieldRefs
      operations: {
        findUnique: {
          args: Prisma.SettingsFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$SettingsPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.SettingsFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$SettingsPayload>
        }
        findFirst: {
          args: Prisma.SettingsFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$SettingsPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.SettingsFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$SettingsPayload>
        }
        findMany: {
          args: Prisma.SettingsFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$SettingsPayload>[]
        }
        create: {
          args: Prisma.SettingsCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$SettingsPayload>
        }
        createMany: {
          args: Prisma.SettingsCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.SettingsCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$SettingsPayload>[]
        }
        delete: {
          args: Prisma.SettingsDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$SettingsPayload>
        }
        update: {
          args: Prisma.SettingsUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$SettingsPayload>
        }
        deleteMany: {
          args: Prisma.SettingsDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.SettingsUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.SettingsUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$SettingsPayload>[]
        }
        upsert: {
          args: Prisma.SettingsUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$SettingsPayload>
        }
        aggregate: {
          args: Prisma.SettingsAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateSettings>
        }
        groupBy: {
          args: Prisma.SettingsGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.SettingsGroupByOutputType>[]
        }
        count: {
          args: Prisma.SettingsCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.SettingsCountAggregateOutputType> | number
        }
      }
    }
    Project: {
      payload: Prisma.$ProjectPayload<ExtArgs>
      fields: Prisma.ProjectFieldRefs
      operations: {
        findUnique: {
          args: Prisma.ProjectFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ProjectPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.ProjectFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ProjectPayload>
        }
        findFirst: {
          args: Prisma.ProjectFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ProjectPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.ProjectFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ProjectPayload>
        }
        findMany: {
          args: Prisma.ProjectFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ProjectPayload>[]
        }
        create: {
          args: Prisma.ProjectCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ProjectPayload>
        }
        createMany: {
          args: Prisma.ProjectCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.ProjectCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ProjectPayload>[]
        }
        delete: {
          args: Prisma.ProjectDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ProjectPayload>
        }
        update: {
          args: Prisma.ProjectUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ProjectPayload>
        }
        deleteMany: {
          args: Prisma.ProjectDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.ProjectUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.ProjectUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ProjectPayload>[]
        }
        upsert: {
          args: Prisma.ProjectUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ProjectPayload>
        }
        aggregate: {
          args: Prisma.ProjectAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateProject>
        }
        groupBy: {
          args: Prisma.ProjectGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.ProjectGroupByOutputType>[]
        }
        count: {
          args: Prisma.ProjectCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.ProjectCountAggregateOutputType> | number
        }
      }
    }
    ProjectSource: {
      payload: Prisma.$ProjectSourcePayload<ExtArgs>
      fields: Prisma.ProjectSourceFieldRefs
      operations: {
        findUnique: {
          args: Prisma.ProjectSourceFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ProjectSourcePayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.ProjectSourceFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ProjectSourcePayload>
        }
        findFirst: {
          args: Prisma.ProjectSourceFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ProjectSourcePayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.ProjectSourceFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ProjectSourcePayload>
        }
        findMany: {
          args: Prisma.ProjectSourceFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ProjectSourcePayload>[]
        }
        create: {
          args: Prisma.ProjectSourceCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ProjectSourcePayload>
        }
        createMany: {
          args: Prisma.ProjectSourceCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.ProjectSourceCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ProjectSourcePayload>[]
        }
        delete: {
          args: Prisma.ProjectSourceDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ProjectSourcePayload>
        }
        update: {
          args: Prisma.ProjectSourceUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ProjectSourcePayload>
        }
        deleteMany: {
          args: Prisma.ProjectSourceDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.ProjectSourceUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.ProjectSourceUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ProjectSourcePayload>[]
        }
        upsert: {
          args: Prisma.ProjectSourceUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ProjectSourcePayload>
        }
        aggregate: {
          args: Prisma.ProjectSourceAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateProjectSource>
        }
        groupBy: {
          args: Prisma.ProjectSourceGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.ProjectSourceGroupByOutputType>[]
        }
        count: {
          args: Prisma.ProjectSourceCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.ProjectSourceCountAggregateOutputType> | number
        }
      }
    }
    Version: {
      payload: Prisma.$VersionPayload<ExtArgs>
      fields: Prisma.VersionFieldRefs
      operations: {
        findUnique: {
          args: Prisma.VersionFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$VersionPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.VersionFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$VersionPayload>
        }
        findFirst: {
          args: Prisma.VersionFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$VersionPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.VersionFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$VersionPayload>
        }
        findMany: {
          args: Prisma.VersionFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$VersionPayload>[]
        }
        create: {
          args: Prisma.VersionCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$VersionPayload>
        }
        createMany: {
          args: Prisma.VersionCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.VersionCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$VersionPayload>[]
        }
        delete: {
          args: Prisma.VersionDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$VersionPayload>
        }
        update: {
          args: Prisma.VersionUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$VersionPayload>
        }
        deleteMany: {
          args: Prisma.VersionDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.VersionUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.VersionUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$VersionPayload>[]
        }
        upsert: {
          args: Prisma.VersionUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$VersionPayload>
        }
        aggregate: {
          args: Prisma.VersionAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateVersion>
        }
        groupBy: {
          args: Prisma.VersionGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.VersionGroupByOutputType>[]
        }
        count: {
          args: Prisma.VersionCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.VersionCountAggregateOutputType> | number
        }
      }
    }
    Content: {
      payload: Prisma.$ContentPayload<ExtArgs>
      fields: Prisma.ContentFieldRefs
      operations: {
        findUnique: {
          args: Prisma.ContentFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ContentPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.ContentFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ContentPayload>
        }
        findFirst: {
          args: Prisma.ContentFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ContentPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.ContentFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ContentPayload>
        }
        findMany: {
          args: Prisma.ContentFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ContentPayload>[]
        }
        create: {
          args: Prisma.ContentCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ContentPayload>
        }
        createMany: {
          args: Prisma.ContentCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.ContentCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ContentPayload>[]
        }
        delete: {
          args: Prisma.ContentDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ContentPayload>
        }
        update: {
          args: Prisma.ContentUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ContentPayload>
        }
        deleteMany: {
          args: Prisma.ContentDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.ContentUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.ContentUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ContentPayload>[]
        }
        upsert: {
          args: Prisma.ContentUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ContentPayload>
        }
        aggregate: {
          args: Prisma.ContentAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateContent>
        }
        groupBy: {
          args: Prisma.ContentGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.ContentGroupByOutputType>[]
        }
        count: {
          args: Prisma.ContentCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.ContentCountAggregateOutputType> | number
        }
      }
    }
    NavStructure: {
      payload: Prisma.$NavStructurePayload<ExtArgs>
      fields: Prisma.NavStructureFieldRefs
      operations: {
        findUnique: {
          args: Prisma.NavStructureFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$NavStructurePayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.NavStructureFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$NavStructurePayload>
        }
        findFirst: {
          args: Prisma.NavStructureFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$NavStructurePayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.NavStructureFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$NavStructurePayload>
        }
        findMany: {
          args: Prisma.NavStructureFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$NavStructurePayload>[]
        }
        create: {
          args: Prisma.NavStructureCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$NavStructurePayload>
        }
        createMany: {
          args: Prisma.NavStructureCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.NavStructureCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$NavStructurePayload>[]
        }
        delete: {
          args: Prisma.NavStructureDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$NavStructurePayload>
        }
        update: {
          args: Prisma.NavStructureUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$NavStructurePayload>
        }
        deleteMany: {
          args: Prisma.NavStructureDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.NavStructureUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.NavStructureUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$NavStructurePayload>[]
        }
        upsert: {
          args: Prisma.NavStructureUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$NavStructurePayload>
        }
        aggregate: {
          args: Prisma.NavStructureAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateNavStructure>
        }
        groupBy: {
          args: Prisma.NavStructureGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.NavStructureGroupByOutputType>[]
        }
        count: {
          args: Prisma.NavStructureCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.NavStructureCountAggregateOutputType> | number
        }
      }
    }
  }
} & {
  other: {
    payload: any
    operations: {
      $executeRaw: {
        args: [query: TemplateStringsArray | Sql, ...values: any[]],
        result: any
      }
      $executeRawUnsafe: {
        args: [query: string, ...values: any[]],
        result: any
      }
      $queryRaw: {
        args: [query: TemplateStringsArray | Sql, ...values: any[]],
        result: any
      }
      $queryRawUnsafe: {
        args: [query: string, ...values: any[]],
        result: any
      }
    }
  }
}

/**
 * Enums
 */

export const TransactionIsolationLevel = runtime.makeStrictEnum({
  ReadUncommitted: 'ReadUncommitted',
  ReadCommitted: 'ReadCommitted',
  RepeatableRead: 'RepeatableRead',
  Serializable: 'Serializable'
} as const)

export type TransactionIsolationLevel = (typeof TransactionIsolationLevel)[keyof typeof TransactionIsolationLevel]


export const RepositoryScalarFieldEnum = {
  id: 'id',
  githubId: 'githubId',
  name: 'name',
  fullName: 'fullName',
  owner: 'owner',
  description: 'description',
  private: 'private',
  published: 'published',
  fork: 'fork',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  pushedAt: 'pushedAt',
  homepage: 'homepage',
  size: 'size',
  stargazersCount: 'stargazersCount',
  watchersCount: 'watchersCount',
  forksCount: 'forksCount',
  openIssuesCount: 'openIssuesCount',
  language: 'language',
  defaultBranch: 'defaultBranch',
  topics: 'topics',
  archived: 'archived',
  disabled: 'disabled',
  syncedAt: 'syncedAt',
  featured: 'featured',
  emoji: 'emoji',
  faIcon: 'faIcon',
  docsPath: 'docsPath'
} as const

export type RepositoryScalarFieldEnum = (typeof RepositoryScalarFieldEnum)[keyof typeof RepositoryScalarFieldEnum]


export const IssueScalarFieldEnum = {
  id: 'id',
  githubId: 'githubId',
  repositoryId: 'repositoryId',
  number: 'number',
  title: 'title',
  body: 'body',
  state: 'state',
  userLogin: 'userLogin',
  userAvatarUrl: 'userAvatarUrl',
  labels: 'labels',
  assignees: 'assignees',
  commentsCount: 'commentsCount',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  closedAt: 'closedAt',
  syncedAt: 'syncedAt'
} as const

export type IssueScalarFieldEnum = (typeof IssueScalarFieldEnum)[keyof typeof IssueScalarFieldEnum]


export const PullRequestScalarFieldEnum = {
  id: 'id',
  githubId: 'githubId',
  repositoryId: 'repositoryId',
  number: 'number',
  title: 'title',
  body: 'body',
  state: 'state',
  userLogin: 'userLogin',
  userAvatarUrl: 'userAvatarUrl',
  labels: 'labels',
  assignees: 'assignees',
  requestedReviewers: 'requestedReviewers',
  headRef: 'headRef',
  baseRef: 'baseRef',
  mergeable: 'mergeable',
  merged: 'merged',
  mergedAt: 'mergedAt',
  mergedBy: 'mergedBy',
  commentsCount: 'commentsCount',
  reviewCommentsCount: 'reviewCommentsCount',
  commitsCount: 'commitsCount',
  additions: 'additions',
  deletions: 'deletions',
  changedFiles: 'changedFiles',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  closedAt: 'closedAt',
  syncedAt: 'syncedAt'
} as const

export type PullRequestScalarFieldEnum = (typeof PullRequestScalarFieldEnum)[keyof typeof PullRequestScalarFieldEnum]


export const CommitScalarFieldEnum = {
  sha: 'sha',
  repositoryId: 'repositoryId',
  message: 'message',
  authorName: 'authorName',
  authorEmail: 'authorEmail',
  authorDate: 'authorDate',
  committerName: 'committerName',
  committerEmail: 'committerEmail',
  committerDate: 'committerDate',
  additions: 'additions',
  deletions: 'deletions',
  totalChanges: 'totalChanges',
  syncedAt: 'syncedAt'
} as const

export type CommitScalarFieldEnum = (typeof CommitScalarFieldEnum)[keyof typeof CommitScalarFieldEnum]


export const ReleaseScalarFieldEnum = {
  id: 'id',
  githubId: 'githubId',
  repositoryId: 'repositoryId',
  tagName: 'tagName',
  name: 'name',
  body: 'body',
  draft: 'draft',
  prerelease: 'prerelease',
  authorLogin: 'authorLogin',
  authorAvatarUrl: 'authorAvatarUrl',
  createdAt: 'createdAt',
  publishedAt: 'publishedAt',
  syncedAt: 'syncedAt'
} as const

export type ReleaseScalarFieldEnum = (typeof ReleaseScalarFieldEnum)[keyof typeof ReleaseScalarFieldEnum]


export const VersionTagScalarFieldEnum = {
  id: 'id',
  repositoryId: 'repositoryId',
  tagName: 'tagName',
  commitSha: 'commitSha',
  isLatest: 'isLatest',
  docsSynced: 'docsSynced',
  docsSyncedAt: 'docsSyncedAt',
  createdAt: 'createdAt',
  syncedAt: 'syncedAt'
} as const

export type VersionTagScalarFieldEnum = (typeof VersionTagScalarFieldEnum)[keyof typeof VersionTagScalarFieldEnum]


export const ContributorScalarFieldEnum = {
  id: 'id',
  githubId: 'githubId',
  login: 'login',
  avatarUrl: 'avatarUrl',
  htmlUrl: 'htmlUrl',
  type: 'type',
  siteAdmin: 'siteAdmin',
  name: 'name',
  company: 'company',
  blog: 'blog',
  location: 'location',
  email: 'email',
  bio: 'bio',
  publicRepos: 'publicRepos',
  publicGists: 'publicGists',
  followers: 'followers',
  following: 'following',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  syncedAt: 'syncedAt'
} as const

export type ContributorScalarFieldEnum = (typeof ContributorScalarFieldEnum)[keyof typeof ContributorScalarFieldEnum]


export const ContributorContributionScalarFieldEnum = {
  contributorId: 'contributorId',
  repositoryId: 'repositoryId',
  contributionsCount: 'contributionsCount',
  syncedAt: 'syncedAt'
} as const

export type ContributorContributionScalarFieldEnum = (typeof ContributorContributionScalarFieldEnum)[keyof typeof ContributorContributionScalarFieldEnum]


export const DocumentationContentScalarFieldEnum = {
  id: 'id',
  repositoryId: 'repositoryId',
  filePath: 'filePath',
  versionTag: 'versionTag',
  slug: 'slug',
  groupSlug: 'groupSlug',
  title: 'title',
  content: 'content',
  description: 'description',
  orderIndex: 'orderIndex',
  version: 'version',
  status: 'status',
  emoji: 'emoji',
  faIcon: 'faIcon',
  hidden: 'hidden',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type DocumentationContentScalarFieldEnum = (typeof DocumentationContentScalarFieldEnum)[keyof typeof DocumentationContentScalarFieldEnum]


export const DocumentationMetadataScalarFieldEnum = {
  id: 'id',
  repositoryId: 'repositoryId',
  versionTag: 'versionTag',
  lastCommitSha: 'lastCommitSha',
  lastSyncedAt: 'lastSyncedAt',
  fileCount: 'fileCount',
  totalSize: 'totalSize'
} as const

export type DocumentationMetadataScalarFieldEnum = (typeof DocumentationMetadataScalarFieldEnum)[keyof typeof DocumentationMetadataScalarFieldEnum]


export const SyncLogScalarFieldEnum = {
  id: 'id',
  syncType: 'syncType',
  repositoryId: 'repositoryId',
  status: 'status',
  startedAt: 'startedAt',
  completedAt: 'completedAt',
  errorMessage: 'errorMessage',
  recordsProcessed: 'recordsProcessed',
  metadata: 'metadata'
} as const

export type SyncLogScalarFieldEnum = (typeof SyncLogScalarFieldEnum)[keyof typeof SyncLogScalarFieldEnum]


export const SettingsScalarFieldEnum = {
  id: 'id',
  key: 'key',
  title: 'title',
  description: 'description',
  section: 'section',
  appliedTo: 'appliedTo',
  type: 'type',
  value: 'value',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type SettingsScalarFieldEnum = (typeof SettingsScalarFieldEnum)[keyof typeof SettingsScalarFieldEnum]


export const ProjectScalarFieldEnum = {
  id: 'id',
  slug: 'slug',
  name: 'name',
  description: 'description',
  published: 'published',
  featured: 'featured',
  emoji: 'emoji',
  faIcon: 'faIcon',
  topics: 'topics',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type ProjectScalarFieldEnum = (typeof ProjectScalarFieldEnum)[keyof typeof ProjectScalarFieldEnum]


export const ProjectSourceScalarFieldEnum = {
  id: 'id',
  projectId: 'projectId',
  provider: 'provider',
  owner: 'owner',
  repo: 'repo',
  fullName: 'fullName',
  defaultBranch: 'defaultBranch',
  docsPath: 'docsPath',
  isPrimary: 'isPrimary',
  lastSyncedAt: 'lastSyncedAt',
  metadata: 'metadata',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type ProjectSourceScalarFieldEnum = (typeof ProjectSourceScalarFieldEnum)[keyof typeof ProjectSourceScalarFieldEnum]


export const VersionScalarFieldEnum = {
  id: 'id',
  projectId: 'projectId',
  tag: 'tag',
  gitRef: 'gitRef',
  isLatest: 'isLatest',
  docsSynced: 'docsSynced',
  syncedAt: 'syncedAt',
  fileCount: 'fileCount',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type VersionScalarFieldEnum = (typeof VersionScalarFieldEnum)[keyof typeof VersionScalarFieldEnum]


export const ContentScalarFieldEnum = {
  id: 'id',
  versionId: 'versionId',
  filePath: 'filePath',
  slug: 'slug',
  title: 'title',
  content: 'content',
  description: 'description',
  emoji: 'emoji',
  faIcon: 'faIcon',
  status: 'status',
  wordCount: 'wordCount',
  byteSize: 'byteSize',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type ContentScalarFieldEnum = (typeof ContentScalarFieldEnum)[keyof typeof ContentScalarFieldEnum]


export const NavStructureScalarFieldEnum = {
  id: 'id',
  projectId: 'projectId',
  parentId: 'parentId',
  slugPattern: 'slugPattern',
  sortOrder: 'sortOrder',
  type: 'type',
  customTitle: 'customTitle',
  customEmoji: 'customEmoji',
  customIcon: 'customIcon',
  externalUrl: 'externalUrl',
  hidden: 'hidden',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type NavStructureScalarFieldEnum = (typeof NavStructureScalarFieldEnum)[keyof typeof NavStructureScalarFieldEnum]


export const SortOrder = {
  asc: 'asc',
  desc: 'desc'
} as const

export type SortOrder = (typeof SortOrder)[keyof typeof SortOrder]


export const JsonNullValueInput = {
  JsonNull: JsonNull
} as const

export type JsonNullValueInput = (typeof JsonNullValueInput)[keyof typeof JsonNullValueInput]


export const QueryMode = {
  default: 'default',
  insensitive: 'insensitive'
} as const

export type QueryMode = (typeof QueryMode)[keyof typeof QueryMode]


export const NullsOrder = {
  first: 'first',
  last: 'last'
} as const

export type NullsOrder = (typeof NullsOrder)[keyof typeof NullsOrder]


export const RepositoryOrderByRelevanceFieldEnum = {
  id: 'id',
  name: 'name',
  fullName: 'fullName',
  owner: 'owner',
  description: 'description',
  homepage: 'homepage',
  language: 'language',
  defaultBranch: 'defaultBranch',
  topics: 'topics',
  emoji: 'emoji',
  faIcon: 'faIcon',
  docsPath: 'docsPath'
} as const

export type RepositoryOrderByRelevanceFieldEnum = (typeof RepositoryOrderByRelevanceFieldEnum)[keyof typeof RepositoryOrderByRelevanceFieldEnum]


export const IssueOrderByRelevanceFieldEnum = {
  id: 'id',
  repositoryId: 'repositoryId',
  title: 'title',
  body: 'body',
  userLogin: 'userLogin',
  userAvatarUrl: 'userAvatarUrl',
  labels: 'labels',
  assignees: 'assignees'
} as const

export type IssueOrderByRelevanceFieldEnum = (typeof IssueOrderByRelevanceFieldEnum)[keyof typeof IssueOrderByRelevanceFieldEnum]


export const PullRequestOrderByRelevanceFieldEnum = {
  id: 'id',
  repositoryId: 'repositoryId',
  title: 'title',
  body: 'body',
  userLogin: 'userLogin',
  userAvatarUrl: 'userAvatarUrl',
  labels: 'labels',
  assignees: 'assignees',
  requestedReviewers: 'requestedReviewers',
  headRef: 'headRef',
  baseRef: 'baseRef',
  mergedBy: 'mergedBy'
} as const

export type PullRequestOrderByRelevanceFieldEnum = (typeof PullRequestOrderByRelevanceFieldEnum)[keyof typeof PullRequestOrderByRelevanceFieldEnum]


export const CommitOrderByRelevanceFieldEnum = {
  sha: 'sha',
  repositoryId: 'repositoryId',
  message: 'message',
  authorName: 'authorName',
  authorEmail: 'authorEmail',
  committerName: 'committerName',
  committerEmail: 'committerEmail'
} as const

export type CommitOrderByRelevanceFieldEnum = (typeof CommitOrderByRelevanceFieldEnum)[keyof typeof CommitOrderByRelevanceFieldEnum]


export const ReleaseOrderByRelevanceFieldEnum = {
  id: 'id',
  repositoryId: 'repositoryId',
  tagName: 'tagName',
  name: 'name',
  body: 'body',
  authorLogin: 'authorLogin',
  authorAvatarUrl: 'authorAvatarUrl'
} as const

export type ReleaseOrderByRelevanceFieldEnum = (typeof ReleaseOrderByRelevanceFieldEnum)[keyof typeof ReleaseOrderByRelevanceFieldEnum]


export const VersionTagOrderByRelevanceFieldEnum = {
  id: 'id',
  repositoryId: 'repositoryId',
  tagName: 'tagName',
  commitSha: 'commitSha'
} as const

export type VersionTagOrderByRelevanceFieldEnum = (typeof VersionTagOrderByRelevanceFieldEnum)[keyof typeof VersionTagOrderByRelevanceFieldEnum]


export const ContributorOrderByRelevanceFieldEnum = {
  id: 'id',
  login: 'login',
  avatarUrl: 'avatarUrl',
  htmlUrl: 'htmlUrl',
  type: 'type',
  name: 'name',
  company: 'company',
  blog: 'blog',
  location: 'location',
  email: 'email',
  bio: 'bio'
} as const

export type ContributorOrderByRelevanceFieldEnum = (typeof ContributorOrderByRelevanceFieldEnum)[keyof typeof ContributorOrderByRelevanceFieldEnum]


export const ContributorContributionOrderByRelevanceFieldEnum = {
  contributorId: 'contributorId',
  repositoryId: 'repositoryId'
} as const

export type ContributorContributionOrderByRelevanceFieldEnum = (typeof ContributorContributionOrderByRelevanceFieldEnum)[keyof typeof ContributorContributionOrderByRelevanceFieldEnum]


export const DocumentationContentOrderByRelevanceFieldEnum = {
  id: 'id',
  repositoryId: 'repositoryId',
  filePath: 'filePath',
  versionTag: 'versionTag',
  slug: 'slug',
  groupSlug: 'groupSlug',
  title: 'title',
  content: 'content',
  description: 'description',
  version: 'version',
  status: 'status',
  emoji: 'emoji',
  faIcon: 'faIcon'
} as const

export type DocumentationContentOrderByRelevanceFieldEnum = (typeof DocumentationContentOrderByRelevanceFieldEnum)[keyof typeof DocumentationContentOrderByRelevanceFieldEnum]


export const DocumentationMetadataOrderByRelevanceFieldEnum = {
  id: 'id',
  repositoryId: 'repositoryId',
  versionTag: 'versionTag',
  lastCommitSha: 'lastCommitSha'
} as const

export type DocumentationMetadataOrderByRelevanceFieldEnum = (typeof DocumentationMetadataOrderByRelevanceFieldEnum)[keyof typeof DocumentationMetadataOrderByRelevanceFieldEnum]


export const JsonNullValueFilter = {
  DbNull: DbNull,
  JsonNull: JsonNull,
  AnyNull: AnyNull
} as const

export type JsonNullValueFilter = (typeof JsonNullValueFilter)[keyof typeof JsonNullValueFilter]


export const SyncLogOrderByRelevanceFieldEnum = {
  id: 'id',
  syncType: 'syncType',
  repositoryId: 'repositoryId',
  errorMessage: 'errorMessage'
} as const

export type SyncLogOrderByRelevanceFieldEnum = (typeof SyncLogOrderByRelevanceFieldEnum)[keyof typeof SyncLogOrderByRelevanceFieldEnum]


export const SettingsOrderByRelevanceFieldEnum = {
  id: 'id',
  key: 'key',
  title: 'title',
  description: 'description',
  section: 'section',
  appliedTo: 'appliedTo',
  type: 'type',
  value: 'value'
} as const

export type SettingsOrderByRelevanceFieldEnum = (typeof SettingsOrderByRelevanceFieldEnum)[keyof typeof SettingsOrderByRelevanceFieldEnum]


export const ProjectOrderByRelevanceFieldEnum = {
  id: 'id',
  slug: 'slug',
  name: 'name',
  description: 'description',
  emoji: 'emoji',
  faIcon: 'faIcon',
  topics: 'topics'
} as const

export type ProjectOrderByRelevanceFieldEnum = (typeof ProjectOrderByRelevanceFieldEnum)[keyof typeof ProjectOrderByRelevanceFieldEnum]


export const ProjectSourceOrderByRelevanceFieldEnum = {
  id: 'id',
  projectId: 'projectId',
  owner: 'owner',
  repo: 'repo',
  fullName: 'fullName',
  defaultBranch: 'defaultBranch',
  docsPath: 'docsPath'
} as const

export type ProjectSourceOrderByRelevanceFieldEnum = (typeof ProjectSourceOrderByRelevanceFieldEnum)[keyof typeof ProjectSourceOrderByRelevanceFieldEnum]


export const VersionOrderByRelevanceFieldEnum = {
  id: 'id',
  projectId: 'projectId',
  tag: 'tag',
  gitRef: 'gitRef'
} as const

export type VersionOrderByRelevanceFieldEnum = (typeof VersionOrderByRelevanceFieldEnum)[keyof typeof VersionOrderByRelevanceFieldEnum]


export const ContentOrderByRelevanceFieldEnum = {
  id: 'id',
  versionId: 'versionId',
  filePath: 'filePath',
  slug: 'slug',
  title: 'title',
  content: 'content',
  description: 'description',
  emoji: 'emoji',
  faIcon: 'faIcon',
  status: 'status'
} as const

export type ContentOrderByRelevanceFieldEnum = (typeof ContentOrderByRelevanceFieldEnum)[keyof typeof ContentOrderByRelevanceFieldEnum]


export const NavStructureOrderByRelevanceFieldEnum = {
  id: 'id',
  projectId: 'projectId',
  parentId: 'parentId',
  slugPattern: 'slugPattern',
  customTitle: 'customTitle',
  customEmoji: 'customEmoji',
  customIcon: 'customIcon',
  externalUrl: 'externalUrl'
} as const

export type NavStructureOrderByRelevanceFieldEnum = (typeof NavStructureOrderByRelevanceFieldEnum)[keyof typeof NavStructureOrderByRelevanceFieldEnum]



/**
 * Field references
 */


/**
 * Reference to a field of type 'String'
 */
export type StringFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'String'>
    


/**
 * Reference to a field of type 'String[]'
 */
export type ListStringFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'String[]'>
    


/**
 * Reference to a field of type 'BigInt'
 */
export type BigIntFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'BigInt'>
    


/**
 * Reference to a field of type 'BigInt[]'
 */
export type ListBigIntFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'BigInt[]'>
    


/**
 * Reference to a field of type 'Boolean'
 */
export type BooleanFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'Boolean'>
    


/**
 * Reference to a field of type 'DateTime'
 */
export type DateTimeFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'DateTime'>
    


/**
 * Reference to a field of type 'DateTime[]'
 */
export type ListDateTimeFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'DateTime[]'>
    


/**
 * Reference to a field of type 'Int'
 */
export type IntFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'Int'>
    


/**
 * Reference to a field of type 'Int[]'
 */
export type ListIntFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'Int[]'>
    


/**
 * Reference to a field of type 'IssueState'
 */
export type EnumIssueStateFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'IssueState'>
    


/**
 * Reference to a field of type 'IssueState[]'
 */
export type ListEnumIssueStateFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'IssueState[]'>
    


/**
 * Reference to a field of type 'PrState'
 */
export type EnumPrStateFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'PrState'>
    


/**
 * Reference to a field of type 'PrState[]'
 */
export type ListEnumPrStateFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'PrState[]'>
    


/**
 * Reference to a field of type 'SyncStatus'
 */
export type EnumSyncStatusFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'SyncStatus'>
    


/**
 * Reference to a field of type 'SyncStatus[]'
 */
export type ListEnumSyncStatusFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'SyncStatus[]'>
    


/**
 * Reference to a field of type 'Json'
 */
export type JsonFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'Json'>
    


/**
 * Reference to a field of type 'QueryMode'
 */
export type EnumQueryModeFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'QueryMode'>
    


/**
 * Reference to a field of type 'SourceProvider'
 */
export type EnumSourceProviderFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'SourceProvider'>
    


/**
 * Reference to a field of type 'SourceProvider[]'
 */
export type ListEnumSourceProviderFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'SourceProvider[]'>
    


/**
 * Reference to a field of type 'NavNodeType'
 */
export type EnumNavNodeTypeFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'NavNodeType'>
    


/**
 * Reference to a field of type 'NavNodeType[]'
 */
export type ListEnumNavNodeTypeFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'NavNodeType[]'>
    


/**
 * Reference to a field of type 'Float'
 */
export type FloatFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'Float'>
    


/**
 * Reference to a field of type 'Float[]'
 */
export type ListFloatFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'Float[]'>
    

/**
 * Batch Payload for updateMany & deleteMany & createMany
 */
export type BatchPayload = {
  count: number
}

export const defineExtension = runtime.Extensions.defineExtension as unknown as runtime.Types.Extensions.ExtendsHook<"define", TypeMapCb, runtime.Types.Extensions.DefaultArgs>
export type DefaultPrismaClient = PrismaClient
export type ErrorFormat = 'pretty' | 'colorless' | 'minimal'
export type PrismaClientOptions = ({
  /**
   * Instance of a Driver Adapter, e.g., like one provided by `@prisma/adapter-pg`.
   */
  adapter: runtime.SqlDriverAdapterFactory
  accelerateUrl?: never
} | {
  /**
   * Prisma Accelerate URL allowing the client to connect through Accelerate instead of a direct database.
   */
  accelerateUrl: string
  adapter?: never
}) & {
  /**
   * @default "colorless"
   */
  errorFormat?: ErrorFormat
  /**
   * @example
   * ```
   * // Shorthand for `emit: 'stdout'`
   * log: ['query', 'info', 'warn', 'error']
   * 
   * // Emit as events only
   * log: [
   *   { emit: 'event', level: 'query' },
   *   { emit: 'event', level: 'info' },
   *   { emit: 'event', level: 'warn' }
   *   { emit: 'event', level: 'error' }
   * ]
   * 
   * / Emit as events and log to stdout
   * og: [
   *  { emit: 'stdout', level: 'query' },
   *  { emit: 'stdout', level: 'info' },
   *  { emit: 'stdout', level: 'warn' }
   *  { emit: 'stdout', level: 'error' }
   * 
   * ```
   * Read more in our [docs](https://www.prisma.io/docs/reference/tools-and-interfaces/prisma-client/logging#the-log-option).
   */
  log?: (LogLevel | LogDefinition)[]
  /**
   * The default values for transactionOptions
   * maxWait ?= 2000
   * timeout ?= 5000
   */
  transactionOptions?: {
    maxWait?: number
    timeout?: number
    isolationLevel?: TransactionIsolationLevel
  }
  /**
   * Global configuration for omitting model fields by default.
   * 
   * @example
   * ```
   * const prisma = new PrismaClient({
   *   omit: {
   *     user: {
   *       password: true
   *     }
   *   }
   * })
   * ```
   */
  omit?: GlobalOmitConfig
}
export type GlobalOmitConfig = {
  repository?: Prisma.RepositoryOmit
  issue?: Prisma.IssueOmit
  pullRequest?: Prisma.PullRequestOmit
  commit?: Prisma.CommitOmit
  release?: Prisma.ReleaseOmit
  versionTag?: Prisma.VersionTagOmit
  contributor?: Prisma.ContributorOmit
  contributorContribution?: Prisma.ContributorContributionOmit
  documentationContent?: Prisma.DocumentationContentOmit
  documentationMetadata?: Prisma.DocumentationMetadataOmit
  syncLog?: Prisma.SyncLogOmit
  settings?: Prisma.SettingsOmit
  project?: Prisma.ProjectOmit
  projectSource?: Prisma.ProjectSourceOmit
  version?: Prisma.VersionOmit
  content?: Prisma.ContentOmit
  navStructure?: Prisma.NavStructureOmit
}

/* Types for Logging */
export type LogLevel = 'info' | 'query' | 'warn' | 'error'
export type LogDefinition = {
  level: LogLevel
  emit: 'stdout' | 'event'
}

export type CheckIsLogLevel<T> = T extends LogLevel ? T : never;

export type GetLogType<T> = CheckIsLogLevel<
  T extends LogDefinition ? T['level'] : T
>;

export type GetEvents<T extends any[]> = T extends Array<LogLevel | LogDefinition>
  ? GetLogType<T[number]>
  : never;

export type QueryEvent = {
  timestamp: Date
  query: string
  params: string
  duration: number
  target: string
}

export type LogEvent = {
  timestamp: Date
  message: string
  target: string
}
/* End Types for Logging */


export type PrismaAction =
  | 'findUnique'
  | 'findUniqueOrThrow'
  | 'findMany'
  | 'findFirst'
  | 'findFirstOrThrow'
  | 'create'
  | 'createMany'
  | 'createManyAndReturn'
  | 'update'
  | 'updateMany'
  | 'updateManyAndReturn'
  | 'upsert'
  | 'delete'
  | 'deleteMany'
  | 'executeRaw'
  | 'queryRaw'
  | 'aggregate'
  | 'count'
  | 'runCommandRaw'
  | 'findRaw'
  | 'groupBy'

/**
 * `PrismaClient` proxy available in interactive transactions.
 */
export type TransactionClient = Omit<DefaultPrismaClient, runtime.ITXClientDenyList>

