
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * WARNING: This is an internal file that is subject to change!
 *
 * 🛑 Under no circumstances should you import this file directly! 🛑
 *
 * All exports from this file are wrapped under a `Prisma` namespace object in the browser.ts file.
 * While this enables partial backward compatibility, it is not part of the stable public API.
 *
 * If you are looking for your Models, Enums, and Input Types, please import them from the respective
 * model files in the `model` directory!
 */

import * as runtime from "@prisma/client/runtime/index-browser"

export type * from '../models'
export type * from './prismaNamespace'

export const Decimal = runtime.Decimal


export const NullTypes = {
  DbNull: runtime.NullTypes.DbNull as (new (secret: never) => typeof runtime.DbNull),
  JsonNull: runtime.NullTypes.JsonNull as (new (secret: never) => typeof runtime.JsonNull),
  AnyNull: runtime.NullTypes.AnyNull as (new (secret: never) => typeof runtime.AnyNull),
}
/**
 * Helper for filtering JSON entries that have `null` on the database (empty on the db)
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const DbNull = runtime.DbNull

/**
 * Helper for filtering JSON entries that have JSON `null` values (not empty on the db)
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const JsonNull = runtime.JsonNull

/**
 * Helper for filtering JSON entries that are `Prisma.DbNull` or `Prisma.JsonNull`
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const AnyNull = runtime.AnyNull


export const ModelName = {
  Repository: 'Repository',
  Issue: 'Issue',
  PullRequest: 'PullRequest',
  Commit: 'Commit',
  Release: 'Release',
  VersionTag: 'VersionTag',
  Contributor: 'Contributor',
  ContributorContribution: 'ContributorContribution',
  DocumentationContent: 'DocumentationContent',
  DocumentationMetadata: 'DocumentationMetadata',
  SyncLog: 'SyncLog',
  Settings: 'Settings',
  Project: 'Project',
  ProjectSource: 'ProjectSource',
  Version: 'Version',
  Content: 'Content',
  NavStructure: 'NavStructure'
} as const

export type ModelName = (typeof ModelName)[keyof typeof ModelName]

/*
 * Enums
 */

export const TransactionIsolationLevel = {
  ReadUncommitted: 'ReadUncommitted',
  ReadCommitted: 'ReadCommitted',
  RepeatableRead: 'RepeatableRead',
  Serializable: 'Serializable'
} as const

export type TransactionIsolationLevel = (typeof TransactionIsolationLevel)[keyof typeof TransactionIsolationLevel]


export const RepositoryScalarFieldEnum = {
  id: 'id',
  githubId: 'githubId',
  name: 'name',
  fullName: 'fullName',
  owner: 'owner',
  description: 'description',
  private: 'private',
  published: 'published',
  fork: 'fork',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  pushedAt: 'pushedAt',
  homepage: 'homepage',
  size: 'size',
  stargazersCount: 'stargazersCount',
  watchersCount: 'watchersCount',
  forksCount: 'forksCount',
  openIssuesCount: 'openIssuesCount',
  language: 'language',
  defaultBranch: 'defaultBranch',
  topics: 'topics',
  archived: 'archived',
  disabled: 'disabled',
  syncedAt: 'syncedAt',
  featured: 'featured',
  emoji: 'emoji',
  faIcon: 'faIcon',
  docsPath: 'docsPath'
} as const

export type RepositoryScalarFieldEnum = (typeof RepositoryScalarFieldEnum)[keyof typeof RepositoryScalarFieldEnum]


export const IssueScalarFieldEnum = {
  id: 'id',
  githubId: 'githubId',
  repositoryId: 'repositoryId',
  number: 'number',
  title: 'title',
  body: 'body',
  state: 'state',
  userLogin: 'userLogin',
  userAvatarUrl: 'userAvatarUrl',
  labels: 'labels',
  assignees: 'assignees',
  commentsCount: 'commentsCount',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  closedAt: 'closedAt',
  syncedAt: 'syncedAt'
} as const

export type IssueScalarFieldEnum = (typeof IssueScalarFieldEnum)[keyof typeof IssueScalarFieldEnum]


export const PullRequestScalarFieldEnum = {
  id: 'id',
  githubId: 'githubId',
  repositoryId: 'repositoryId',
  number: 'number',
  title: 'title',
  body: 'body',
  state: 'state',
  userLogin: 'userLogin',
  userAvatarUrl: 'userAvatarUrl',
  labels: 'labels',
  assignees: 'assignees',
  requestedReviewers: 'requestedReviewers',
  headRef: 'headRef',
  baseRef: 'baseRef',
  mergeable: 'mergeable',
  merged: 'merged',
  mergedAt: 'mergedAt',
  mergedBy: 'mergedBy',
  commentsCount: 'commentsCount',
  reviewCommentsCount: 'reviewCommentsCount',
  commitsCount: 'commitsCount',
  additions: 'additions',
  deletions: 'deletions',
  changedFiles: 'changedFiles',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  closedAt: 'closedAt',
  syncedAt: 'syncedAt'
} as const

export type PullRequestScalarFieldEnum = (typeof PullRequestScalarFieldEnum)[keyof typeof PullRequestScalarFieldEnum]


export const CommitScalarFieldEnum = {
  sha: 'sha',
  repositoryId: 'repositoryId',
  message: 'message',
  authorName: 'authorName',
  authorEmail: 'authorEmail',
  authorDate: 'authorDate',
  committerName: 'committerName',
  committerEmail: 'committerEmail',
  committerDate: 'committerDate',
  additions: 'additions',
  deletions: 'deletions',
  totalChanges: 'totalChanges',
  syncedAt: 'syncedAt'
} as const

export type CommitScalarFieldEnum = (typeof CommitScalarFieldEnum)[keyof typeof CommitScalarFieldEnum]


export const ReleaseScalarFieldEnum = {
  id: 'id',
  githubId: 'githubId',
  repositoryId: 'repositoryId',
  tagName: 'tagName',
  name: 'name',
  body: 'body',
  draft: 'draft',
  prerelease: 'prerelease',
  authorLogin: 'authorLogin',
  authorAvatarUrl: 'authorAvatarUrl',
  createdAt: 'createdAt',
  publishedAt: 'publishedAt',
  syncedAt: 'syncedAt'
} as const

export type ReleaseScalarFieldEnum = (typeof ReleaseScalarFieldEnum)[keyof typeof ReleaseScalarFieldEnum]


export const VersionTagScalarFieldEnum = {
  id: 'id',
  repositoryId: 'repositoryId',
  tagName: 'tagName',
  commitSha: 'commitSha',
  isLatest: 'isLatest',
  docsSynced: 'docsSynced',
  docsSyncedAt: 'docsSyncedAt',
  createdAt: 'createdAt',
  syncedAt: 'syncedAt'
} as const

export type VersionTagScalarFieldEnum = (typeof VersionTagScalarFieldEnum)[keyof typeof VersionTagScalarFieldEnum]


export const ContributorScalarFieldEnum = {
  id: 'id',
  githubId: 'githubId',
  login: 'login',
  avatarUrl: 'avatarUrl',
  htmlUrl: 'htmlUrl',
  type: 'type',
  siteAdmin: 'siteAdmin',
  name: 'name',
  company: 'company',
  blog: 'blog',
  location: 'location',
  email: 'email',
  bio: 'bio',
  publicRepos: 'publicRepos',
  publicGists: 'publicGists',
  followers: 'followers',
  following: 'following',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  syncedAt: 'syncedAt'
} as const

export type ContributorScalarFieldEnum = (typeof ContributorScalarFieldEnum)[keyof typeof ContributorScalarFieldEnum]


export const ContributorContributionScalarFieldEnum = {
  contributorId: 'contributorId',
  repositoryId: 'repositoryId',
  contributionsCount: 'contributionsCount',
  syncedAt: 'syncedAt'
} as const

export type ContributorContributionScalarFieldEnum = (typeof ContributorContributionScalarFieldEnum)[keyof typeof ContributorContributionScalarFieldEnum]


export const DocumentationContentScalarFieldEnum = {
  id: 'id',
  repositoryId: 'repositoryId',
  filePath: 'filePath',
  versionTag: 'versionTag',
  slug: 'slug',
  groupSlug: 'groupSlug',
  title: 'title',
  content: 'content',
  description: 'description',
  orderIndex: 'orderIndex',
  version: 'version',
  status: 'status',
  emoji: 'emoji',
  faIcon: 'faIcon',
  hidden: 'hidden',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type DocumentationContentScalarFieldEnum = (typeof DocumentationContentScalarFieldEnum)[keyof typeof DocumentationContentScalarFieldEnum]


export const DocumentationMetadataScalarFieldEnum = {
  id: 'id',
  repositoryId: 'repositoryId',
  versionTag: 'versionTag',
  lastCommitSha: 'lastCommitSha',
  lastSyncedAt: 'lastSyncedAt',
  fileCount: 'fileCount',
  totalSize: 'totalSize'
} as const

export type DocumentationMetadataScalarFieldEnum = (typeof DocumentationMetadataScalarFieldEnum)[keyof typeof DocumentationMetadataScalarFieldEnum]


export const SyncLogScalarFieldEnum = {
  id: 'id',
  syncType: 'syncType',
  repositoryId: 'repositoryId',
  status: 'status',
  startedAt: 'startedAt',
  completedAt: 'completedAt',
  errorMessage: 'errorMessage',
  recordsProcessed: 'recordsProcessed',
  metadata: 'metadata'
} as const

export type SyncLogScalarFieldEnum = (typeof SyncLogScalarFieldEnum)[keyof typeof SyncLogScalarFieldEnum]


export const SettingsScalarFieldEnum = {
  id: 'id',
  key: 'key',
  title: 'title',
  description: 'description',
  section: 'section',
  appliedTo: 'appliedTo',
  type: 'type',
  value: 'value',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type SettingsScalarFieldEnum = (typeof SettingsScalarFieldEnum)[keyof typeof SettingsScalarFieldEnum]


export const ProjectScalarFieldEnum = {
  id: 'id',
  slug: 'slug',
  name: 'name',
  description: 'description',
  published: 'published',
  featured: 'featured',
  emoji: 'emoji',
  faIcon: 'faIcon',
  topics: 'topics',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type ProjectScalarFieldEnum = (typeof ProjectScalarFieldEnum)[keyof typeof ProjectScalarFieldEnum]


export const ProjectSourceScalarFieldEnum = {
  id: 'id',
  projectId: 'projectId',
  provider: 'provider',
  owner: 'owner',
  repo: 'repo',
  fullName: 'fullName',
  defaultBranch: 'defaultBranch',
  docsPath: 'docsPath',
  isPrimary: 'isPrimary',
  lastSyncedAt: 'lastSyncedAt',
  metadata: 'metadata',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type ProjectSourceScalarFieldEnum = (typeof ProjectSourceScalarFieldEnum)[keyof typeof ProjectSourceScalarFieldEnum]


export const VersionScalarFieldEnum = {
  id: 'id',
  projectId: 'projectId',
  tag: 'tag',
  gitRef: 'gitRef',
  isLatest: 'isLatest',
  docsSynced: 'docsSynced',
  syncedAt: 'syncedAt',
  fileCount: 'fileCount',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type VersionScalarFieldEnum = (typeof VersionScalarFieldEnum)[keyof typeof VersionScalarFieldEnum]


export const ContentScalarFieldEnum = {
  id: 'id',
  versionId: 'versionId',
  filePath: 'filePath',
  slug: 'slug',
  title: 'title',
  content: 'content',
  description: 'description',
  emoji: 'emoji',
  faIcon: 'faIcon',
  status: 'status',
  wordCount: 'wordCount',
  byteSize: 'byteSize',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type ContentScalarFieldEnum = (typeof ContentScalarFieldEnum)[keyof typeof ContentScalarFieldEnum]


export const NavStructureScalarFieldEnum = {
  id: 'id',
  projectId: 'projectId',
  parentId: 'parentId',
  slugPattern: 'slugPattern',
  sortOrder: 'sortOrder',
  type: 'type',
  customTitle: 'customTitle',
  customEmoji: 'customEmoji',
  customIcon: 'customIcon',
  externalUrl: 'externalUrl',
  hidden: 'hidden',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type NavStructureScalarFieldEnum = (typeof NavStructureScalarFieldEnum)[keyof typeof NavStructureScalarFieldEnum]


export const SortOrder = {
  asc: 'asc',
  desc: 'desc'
} as const

export type SortOrder = (typeof SortOrder)[keyof typeof SortOrder]


export const JsonNullValueInput = {
  JsonNull: 'JsonNull'
} as const

export type JsonNullValueInput = (typeof JsonNullValueInput)[keyof typeof JsonNullValueInput]


export const QueryMode = {
  default: 'default',
  insensitive: 'insensitive'
} as const

export type QueryMode = (typeof QueryMode)[keyof typeof QueryMode]


export const NullsOrder = {
  first: 'first',
  last: 'last'
} as const

export type NullsOrder = (typeof NullsOrder)[keyof typeof NullsOrder]


export const RepositoryOrderByRelevanceFieldEnum = {
  id: 'id',
  name: 'name',
  fullName: 'fullName',
  owner: 'owner',
  description: 'description',
  homepage: 'homepage',
  language: 'language',
  defaultBranch: 'defaultBranch',
  topics: 'topics',
  emoji: 'emoji',
  faIcon: 'faIcon',
  docsPath: 'docsPath'
} as const

export type RepositoryOrderByRelevanceFieldEnum = (typeof RepositoryOrderByRelevanceFieldEnum)[keyof typeof RepositoryOrderByRelevanceFieldEnum]


export const IssueOrderByRelevanceFieldEnum = {
  id: 'id',
  repositoryId: 'repositoryId',
  title: 'title',
  body: 'body',
  userLogin: 'userLogin',
  userAvatarUrl: 'userAvatarUrl',
  labels: 'labels',
  assignees: 'assignees'
} as const

export type IssueOrderByRelevanceFieldEnum = (typeof IssueOrderByRelevanceFieldEnum)[keyof typeof IssueOrderByRelevanceFieldEnum]


export const PullRequestOrderByRelevanceFieldEnum = {
  id: 'id',
  repositoryId: 'repositoryId',
  title: 'title',
  body: 'body',
  userLogin: 'userLogin',
  userAvatarUrl: 'userAvatarUrl',
  labels: 'labels',
  assignees: 'assignees',
  requestedReviewers: 'requestedReviewers',
  headRef: 'headRef',
  baseRef: 'baseRef',
  mergedBy: 'mergedBy'
} as const

export type PullRequestOrderByRelevanceFieldEnum = (typeof PullRequestOrderByRelevanceFieldEnum)[keyof typeof PullRequestOrderByRelevanceFieldEnum]


export const CommitOrderByRelevanceFieldEnum = {
  sha: 'sha',
  repositoryId: 'repositoryId',
  message: 'message',
  authorName: 'authorName',
  authorEmail: 'authorEmail',
  committerName: 'committerName',
  committerEmail: 'committerEmail'
} as const

export type CommitOrderByRelevanceFieldEnum = (typeof CommitOrderByRelevanceFieldEnum)[keyof typeof CommitOrderByRelevanceFieldEnum]


export const ReleaseOrderByRelevanceFieldEnum = {
  id: 'id',
  repositoryId: 'repositoryId',
  tagName: 'tagName',
  name: 'name',
  body: 'body',
  authorLogin: 'authorLogin',
  authorAvatarUrl: 'authorAvatarUrl'
} as const

export type ReleaseOrderByRelevanceFieldEnum = (typeof ReleaseOrderByRelevanceFieldEnum)[keyof typeof ReleaseOrderByRelevanceFieldEnum]


export const VersionTagOrderByRelevanceFieldEnum = {
  id: 'id',
  repositoryId: 'repositoryId',
  tagName: 'tagName',
  commitSha: 'commitSha'
} as const

export type VersionTagOrderByRelevanceFieldEnum = (typeof VersionTagOrderByRelevanceFieldEnum)[keyof typeof VersionTagOrderByRelevanceFieldEnum]


export const ContributorOrderByRelevanceFieldEnum = {
  id: 'id',
  login: 'login',
  avatarUrl: 'avatarUrl',
  htmlUrl: 'htmlUrl',
  type: 'type',
  name: 'name',
  company: 'company',
  blog: 'blog',
  location: 'location',
  email: 'email',
  bio: 'bio'
} as const

export type ContributorOrderByRelevanceFieldEnum = (typeof ContributorOrderByRelevanceFieldEnum)[keyof typeof ContributorOrderByRelevanceFieldEnum]


export const ContributorContributionOrderByRelevanceFieldEnum = {
  contributorId: 'contributorId',
  repositoryId: 'repositoryId'
} as const

export type ContributorContributionOrderByRelevanceFieldEnum = (typeof ContributorContributionOrderByRelevanceFieldEnum)[keyof typeof ContributorContributionOrderByRelevanceFieldEnum]


export const DocumentationContentOrderByRelevanceFieldEnum = {
  id: 'id',
  repositoryId: 'repositoryId',
  filePath: 'filePath',
  versionTag: 'versionTag',
  slug: 'slug',
  groupSlug: 'groupSlug',
  title: 'title',
  content: 'content',
  description: 'description',
  version: 'version',
  status: 'status',
  emoji: 'emoji',
  faIcon: 'faIcon'
} as const

export type DocumentationContentOrderByRelevanceFieldEnum = (typeof DocumentationContentOrderByRelevanceFieldEnum)[keyof typeof DocumentationContentOrderByRelevanceFieldEnum]


export const DocumentationMetadataOrderByRelevanceFieldEnum = {
  id: 'id',
  repositoryId: 'repositoryId',
  versionTag: 'versionTag',
  lastCommitSha: 'lastCommitSha'
} as const

export type DocumentationMetadataOrderByRelevanceFieldEnum = (typeof DocumentationMetadataOrderByRelevanceFieldEnum)[keyof typeof DocumentationMetadataOrderByRelevanceFieldEnum]


export const JsonNullValueFilter = {
  DbNull: 'DbNull',
  JsonNull: 'JsonNull',
  AnyNull: 'AnyNull'
} as const

export type JsonNullValueFilter = (typeof JsonNullValueFilter)[keyof typeof JsonNullValueFilter]


export const SyncLogOrderByRelevanceFieldEnum = {
  id: 'id',
  syncType: 'syncType',
  repositoryId: 'repositoryId',
  errorMessage: 'errorMessage'
} as const

export type SyncLogOrderByRelevanceFieldEnum = (typeof SyncLogOrderByRelevanceFieldEnum)[keyof typeof SyncLogOrderByRelevanceFieldEnum]


export const SettingsOrderByRelevanceFieldEnum = {
  id: 'id',
  key: 'key',
  title: 'title',
  description: 'description',
  section: 'section',
  appliedTo: 'appliedTo',
  type: 'type',
  value: 'value'
} as const

export type SettingsOrderByRelevanceFieldEnum = (typeof SettingsOrderByRelevanceFieldEnum)[keyof typeof SettingsOrderByRelevanceFieldEnum]


export const ProjectOrderByRelevanceFieldEnum = {
  id: 'id',
  slug: 'slug',
  name: 'name',
  description: 'description',
  emoji: 'emoji',
  faIcon: 'faIcon',
  topics: 'topics'
} as const

export type ProjectOrderByRelevanceFieldEnum = (typeof ProjectOrderByRelevanceFieldEnum)[keyof typeof ProjectOrderByRelevanceFieldEnum]


export const ProjectSourceOrderByRelevanceFieldEnum = {
  id: 'id',
  projectId: 'projectId',
  owner: 'owner',
  repo: 'repo',
  fullName: 'fullName',
  defaultBranch: 'defaultBranch',
  docsPath: 'docsPath'
} as const

export type ProjectSourceOrderByRelevanceFieldEnum = (typeof ProjectSourceOrderByRelevanceFieldEnum)[keyof typeof ProjectSourceOrderByRelevanceFieldEnum]


export const VersionOrderByRelevanceFieldEnum = {
  id: 'id',
  projectId: 'projectId',
  tag: 'tag',
  gitRef: 'gitRef'
} as const

export type VersionOrderByRelevanceFieldEnum = (typeof VersionOrderByRelevanceFieldEnum)[keyof typeof VersionOrderByRelevanceFieldEnum]


export const ContentOrderByRelevanceFieldEnum = {
  id: 'id',
  versionId: 'versionId',
  filePath: 'filePath',
  slug: 'slug',
  title: 'title',
  content: 'content',
  description: 'description',
  emoji: 'emoji',
  faIcon: 'faIcon',
  status: 'status'
} as const

export type ContentOrderByRelevanceFieldEnum = (typeof ContentOrderByRelevanceFieldEnum)[keyof typeof ContentOrderByRelevanceFieldEnum]


export const NavStructureOrderByRelevanceFieldEnum = {
  id: 'id',
  projectId: 'projectId',
  parentId: 'parentId',
  slugPattern: 'slugPattern',
  customTitle: 'customTitle',
  customEmoji: 'customEmoji',
  customIcon: 'customIcon',
  externalUrl: 'externalUrl'
} as const

export type NavStructureOrderByRelevanceFieldEnum = (typeof NavStructureOrderByRelevanceFieldEnum)[keyof typeof NavStructureOrderByRelevanceFieldEnum]

