[build]
  command = "pnpm turbo run build --filter=www"
  publish = "apps/www/.next"
  ignore = "git diff --quiet $CACHED_COMMIT_REF $COMMIT_REF -- apps/docs apps/hub"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[build.environment]
  NODE_VERSION = "22"
  NPM_FLAGS = "--legacy-peer-deps"
  SECRETS_SCAN_OMIT_PATHS = "apps/docs,apps/hub"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[context.production]
  command = "pnpm turbo run build --filter=www"

[context.deploy-preview]
  command = "pnpm turbo run build --filter=www"

[context.branch-deploy]
  command = "pnpm turbo run build --filter=www"


# Environment variables needed (set in Netlify UI):
# - NEXT_PUBLIC_BASE_URL
# - HUB_API_KEY
# - HUB_API_URL 