
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `ContributorContribution` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model ContributorContribution
 * 
 */
export type ContributorContributionModel = runtime.Types.Result.DefaultSelection<Prisma.$ContributorContributionPayload>

export type AggregateContributorContribution = {
  _count: ContributorContributionCountAggregateOutputType | null
  _avg: ContributorContributionAvgAggregateOutputType | null
  _sum: ContributorContributionSumAggregateOutputType | null
  _min: ContributorContributionMinAggregateOutputType | null
  _max: ContributorContributionMaxAggregateOutputType | null
}

export type ContributorContributionAvgAggregateOutputType = {
  contributionsCount: number | null
}

export type ContributorContributionSumAggregateOutputType = {
  contributionsCount: number | null
}

export type ContributorContributionMinAggregateOutputType = {
  contributorId: string | null
  repositoryId: string | null
  contributionsCount: number | null
  syncedAt: Date | null
}

export type ContributorContributionMaxAggregateOutputType = {
  contributorId: string | null
  repositoryId: string | null
  contributionsCount: number | null
  syncedAt: Date | null
}

export type ContributorContributionCountAggregateOutputType = {
  contributorId: number
  repositoryId: number
  contributionsCount: number
  syncedAt: number
  _all: number
}


export type ContributorContributionAvgAggregateInputType = {
  contributionsCount?: true
}

export type ContributorContributionSumAggregateInputType = {
  contributionsCount?: true
}

export type ContributorContributionMinAggregateInputType = {
  contributorId?: true
  repositoryId?: true
  contributionsCount?: true
  syncedAt?: true
}

export type ContributorContributionMaxAggregateInputType = {
  contributorId?: true
  repositoryId?: true
  contributionsCount?: true
  syncedAt?: true
}

export type ContributorContributionCountAggregateInputType = {
  contributorId?: true
  repositoryId?: true
  contributionsCount?: true
  syncedAt?: true
  _all?: true
}

export type ContributorContributionAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which ContributorContribution to aggregate.
   */
  where?: Prisma.ContributorContributionWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ContributorContributions to fetch.
   */
  orderBy?: Prisma.ContributorContributionOrderByWithRelationInput | Prisma.ContributorContributionOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.ContributorContributionWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ContributorContributions from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ContributorContributions.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned ContributorContributions
  **/
  _count?: true | ContributorContributionCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: ContributorContributionAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: ContributorContributionSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: ContributorContributionMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: ContributorContributionMaxAggregateInputType
}

export type GetContributorContributionAggregateType<T extends ContributorContributionAggregateArgs> = {
      [P in keyof T & keyof AggregateContributorContribution]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateContributorContribution[P]>
    : Prisma.GetScalarType<T[P], AggregateContributorContribution[P]>
}




export type ContributorContributionGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.ContributorContributionWhereInput
  orderBy?: Prisma.ContributorContributionOrderByWithAggregationInput | Prisma.ContributorContributionOrderByWithAggregationInput[]
  by: Prisma.ContributorContributionScalarFieldEnum[] | Prisma.ContributorContributionScalarFieldEnum
  having?: Prisma.ContributorContributionScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: ContributorContributionCountAggregateInputType | true
  _avg?: ContributorContributionAvgAggregateInputType
  _sum?: ContributorContributionSumAggregateInputType
  _min?: ContributorContributionMinAggregateInputType
  _max?: ContributorContributionMaxAggregateInputType
}

export type ContributorContributionGroupByOutputType = {
  contributorId: string
  repositoryId: string
  contributionsCount: number
  syncedAt: Date
  _count: ContributorContributionCountAggregateOutputType | null
  _avg: ContributorContributionAvgAggregateOutputType | null
  _sum: ContributorContributionSumAggregateOutputType | null
  _min: ContributorContributionMinAggregateOutputType | null
  _max: ContributorContributionMaxAggregateOutputType | null
}

type GetContributorContributionGroupByPayload<T extends ContributorContributionGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<ContributorContributionGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof ContributorContributionGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], ContributorContributionGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], ContributorContributionGroupByOutputType[P]>
      }
    >
  >



export type ContributorContributionWhereInput = {
  AND?: Prisma.ContributorContributionWhereInput | Prisma.ContributorContributionWhereInput[]
  OR?: Prisma.ContributorContributionWhereInput[]
  NOT?: Prisma.ContributorContributionWhereInput | Prisma.ContributorContributionWhereInput[]
  contributorId?: Prisma.StringFilter<"ContributorContribution"> | string
  repositoryId?: Prisma.StringFilter<"ContributorContribution"> | string
  contributionsCount?: Prisma.IntFilter<"ContributorContribution"> | number
  syncedAt?: Prisma.DateTimeFilter<"ContributorContribution"> | Date | string
  contributor?: Prisma.XOR<Prisma.ContributorScalarRelationFilter, Prisma.ContributorWhereInput>
  repository?: Prisma.XOR<Prisma.RepositoryScalarRelationFilter, Prisma.RepositoryWhereInput>
}

export type ContributorContributionOrderByWithRelationInput = {
  contributorId?: Prisma.SortOrder
  repositoryId?: Prisma.SortOrder
  contributionsCount?: Prisma.SortOrder
  syncedAt?: Prisma.SortOrder
  contributor?: Prisma.ContributorOrderByWithRelationInput
  repository?: Prisma.RepositoryOrderByWithRelationInput
  _relevance?: Prisma.ContributorContributionOrderByRelevanceInput
}

export type ContributorContributionWhereUniqueInput = Prisma.AtLeast<{
  contributorId_repositoryId?: Prisma.ContributorContributionContributorIdRepositoryIdCompoundUniqueInput
  AND?: Prisma.ContributorContributionWhereInput | Prisma.ContributorContributionWhereInput[]
  OR?: Prisma.ContributorContributionWhereInput[]
  NOT?: Prisma.ContributorContributionWhereInput | Prisma.ContributorContributionWhereInput[]
  contributorId?: Prisma.StringFilter<"ContributorContribution"> | string
  repositoryId?: Prisma.StringFilter<"ContributorContribution"> | string
  contributionsCount?: Prisma.IntFilter<"ContributorContribution"> | number
  syncedAt?: Prisma.DateTimeFilter<"ContributorContribution"> | Date | string
  contributor?: Prisma.XOR<Prisma.ContributorScalarRelationFilter, Prisma.ContributorWhereInput>
  repository?: Prisma.XOR<Prisma.RepositoryScalarRelationFilter, Prisma.RepositoryWhereInput>
}, "contributorId_repositoryId">

export type ContributorContributionOrderByWithAggregationInput = {
  contributorId?: Prisma.SortOrder
  repositoryId?: Prisma.SortOrder
  contributionsCount?: Prisma.SortOrder
  syncedAt?: Prisma.SortOrder
  _count?: Prisma.ContributorContributionCountOrderByAggregateInput
  _avg?: Prisma.ContributorContributionAvgOrderByAggregateInput
  _max?: Prisma.ContributorContributionMaxOrderByAggregateInput
  _min?: Prisma.ContributorContributionMinOrderByAggregateInput
  _sum?: Prisma.ContributorContributionSumOrderByAggregateInput
}

export type ContributorContributionScalarWhereWithAggregatesInput = {
  AND?: Prisma.ContributorContributionScalarWhereWithAggregatesInput | Prisma.ContributorContributionScalarWhereWithAggregatesInput[]
  OR?: Prisma.ContributorContributionScalarWhereWithAggregatesInput[]
  NOT?: Prisma.ContributorContributionScalarWhereWithAggregatesInput | Prisma.ContributorContributionScalarWhereWithAggregatesInput[]
  contributorId?: Prisma.StringWithAggregatesFilter<"ContributorContribution"> | string
  repositoryId?: Prisma.StringWithAggregatesFilter<"ContributorContribution"> | string
  contributionsCount?: Prisma.IntWithAggregatesFilter<"ContributorContribution"> | number
  syncedAt?: Prisma.DateTimeWithAggregatesFilter<"ContributorContribution"> | Date | string
}

export type ContributorContributionCreateInput = {
  contributionsCount?: number
  syncedAt?: Date | string
  contributor: Prisma.ContributorCreateNestedOneWithoutContributionsInput
  repository: Prisma.RepositoryCreateNestedOneWithoutContributionsInput
}

export type ContributorContributionUncheckedCreateInput = {
  contributorId: string
  repositoryId: string
  contributionsCount?: number
  syncedAt?: Date | string
}

export type ContributorContributionUpdateInput = {
  contributionsCount?: Prisma.IntFieldUpdateOperationsInput | number
  syncedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  contributor?: Prisma.ContributorUpdateOneRequiredWithoutContributionsNestedInput
  repository?: Prisma.RepositoryUpdateOneRequiredWithoutContributionsNestedInput
}

export type ContributorContributionUncheckedUpdateInput = {
  contributorId?: Prisma.StringFieldUpdateOperationsInput | string
  repositoryId?: Prisma.StringFieldUpdateOperationsInput | string
  contributionsCount?: Prisma.IntFieldUpdateOperationsInput | number
  syncedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type ContributorContributionCreateManyInput = {
  contributorId: string
  repositoryId: string
  contributionsCount?: number
  syncedAt?: Date | string
}

export type ContributorContributionUpdateManyMutationInput = {
  contributionsCount?: Prisma.IntFieldUpdateOperationsInput | number
  syncedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type ContributorContributionUncheckedUpdateManyInput = {
  contributorId?: Prisma.StringFieldUpdateOperationsInput | string
  repositoryId?: Prisma.StringFieldUpdateOperationsInput | string
  contributionsCount?: Prisma.IntFieldUpdateOperationsInput | number
  syncedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type ContributorContributionListRelationFilter = {
  every?: Prisma.ContributorContributionWhereInput
  some?: Prisma.ContributorContributionWhereInput
  none?: Prisma.ContributorContributionWhereInput
}

export type ContributorContributionOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type ContributorContributionOrderByRelevanceInput = {
  fields: Prisma.ContributorContributionOrderByRelevanceFieldEnum | Prisma.ContributorContributionOrderByRelevanceFieldEnum[]
  sort: Prisma.SortOrder
  search: string
}

export type ContributorContributionContributorIdRepositoryIdCompoundUniqueInput = {
  contributorId: string
  repositoryId: string
}

export type ContributorContributionCountOrderByAggregateInput = {
  contributorId?: Prisma.SortOrder
  repositoryId?: Prisma.SortOrder
  contributionsCount?: Prisma.SortOrder
  syncedAt?: Prisma.SortOrder
}

export type ContributorContributionAvgOrderByAggregateInput = {
  contributionsCount?: Prisma.SortOrder
}

export type ContributorContributionMaxOrderByAggregateInput = {
  contributorId?: Prisma.SortOrder
  repositoryId?: Prisma.SortOrder
  contributionsCount?: Prisma.SortOrder
  syncedAt?: Prisma.SortOrder
}

export type ContributorContributionMinOrderByAggregateInput = {
  contributorId?: Prisma.SortOrder
  repositoryId?: Prisma.SortOrder
  contributionsCount?: Prisma.SortOrder
  syncedAt?: Prisma.SortOrder
}

export type ContributorContributionSumOrderByAggregateInput = {
  contributionsCount?: Prisma.SortOrder
}

export type ContributorContributionCreateNestedManyWithoutRepositoryInput = {
  create?: Prisma.XOR<Prisma.ContributorContributionCreateWithoutRepositoryInput, Prisma.ContributorContributionUncheckedCreateWithoutRepositoryInput> | Prisma.ContributorContributionCreateWithoutRepositoryInput[] | Prisma.ContributorContributionUncheckedCreateWithoutRepositoryInput[]
  connectOrCreate?: Prisma.ContributorContributionCreateOrConnectWithoutRepositoryInput | Prisma.ContributorContributionCreateOrConnectWithoutRepositoryInput[]
  createMany?: Prisma.ContributorContributionCreateManyRepositoryInputEnvelope
  connect?: Prisma.ContributorContributionWhereUniqueInput | Prisma.ContributorContributionWhereUniqueInput[]
}

export type ContributorContributionUncheckedCreateNestedManyWithoutRepositoryInput = {
  create?: Prisma.XOR<Prisma.ContributorContributionCreateWithoutRepositoryInput, Prisma.ContributorContributionUncheckedCreateWithoutRepositoryInput> | Prisma.ContributorContributionCreateWithoutRepositoryInput[] | Prisma.ContributorContributionUncheckedCreateWithoutRepositoryInput[]
  connectOrCreate?: Prisma.ContributorContributionCreateOrConnectWithoutRepositoryInput | Prisma.ContributorContributionCreateOrConnectWithoutRepositoryInput[]
  createMany?: Prisma.ContributorContributionCreateManyRepositoryInputEnvelope
  connect?: Prisma.ContributorContributionWhereUniqueInput | Prisma.ContributorContributionWhereUniqueInput[]
}

export type ContributorContributionUpdateManyWithoutRepositoryNestedInput = {
  create?: Prisma.XOR<Prisma.ContributorContributionCreateWithoutRepositoryInput, Prisma.ContributorContributionUncheckedCreateWithoutRepositoryInput> | Prisma.ContributorContributionCreateWithoutRepositoryInput[] | Prisma.ContributorContributionUncheckedCreateWithoutRepositoryInput[]
  connectOrCreate?: Prisma.ContributorContributionCreateOrConnectWithoutRepositoryInput | Prisma.ContributorContributionCreateOrConnectWithoutRepositoryInput[]
  upsert?: Prisma.ContributorContributionUpsertWithWhereUniqueWithoutRepositoryInput | Prisma.ContributorContributionUpsertWithWhereUniqueWithoutRepositoryInput[]
  createMany?: Prisma.ContributorContributionCreateManyRepositoryInputEnvelope
  set?: Prisma.ContributorContributionWhereUniqueInput | Prisma.ContributorContributionWhereUniqueInput[]
  disconnect?: Prisma.ContributorContributionWhereUniqueInput | Prisma.ContributorContributionWhereUniqueInput[]
  delete?: Prisma.ContributorContributionWhereUniqueInput | Prisma.ContributorContributionWhereUniqueInput[]
  connect?: Prisma.ContributorContributionWhereUniqueInput | Prisma.ContributorContributionWhereUniqueInput[]
  update?: Prisma.ContributorContributionUpdateWithWhereUniqueWithoutRepositoryInput | Prisma.ContributorContributionUpdateWithWhereUniqueWithoutRepositoryInput[]
  updateMany?: Prisma.ContributorContributionUpdateManyWithWhereWithoutRepositoryInput | Prisma.ContributorContributionUpdateManyWithWhereWithoutRepositoryInput[]
  deleteMany?: Prisma.ContributorContributionScalarWhereInput | Prisma.ContributorContributionScalarWhereInput[]
}

export type ContributorContributionUncheckedUpdateManyWithoutRepositoryNestedInput = {
  create?: Prisma.XOR<Prisma.ContributorContributionCreateWithoutRepositoryInput, Prisma.ContributorContributionUncheckedCreateWithoutRepositoryInput> | Prisma.ContributorContributionCreateWithoutRepositoryInput[] | Prisma.ContributorContributionUncheckedCreateWithoutRepositoryInput[]
  connectOrCreate?: Prisma.ContributorContributionCreateOrConnectWithoutRepositoryInput | Prisma.ContributorContributionCreateOrConnectWithoutRepositoryInput[]
  upsert?: Prisma.ContributorContributionUpsertWithWhereUniqueWithoutRepositoryInput | Prisma.ContributorContributionUpsertWithWhereUniqueWithoutRepositoryInput[]
  createMany?: Prisma.ContributorContributionCreateManyRepositoryInputEnvelope
  set?: Prisma.ContributorContributionWhereUniqueInput | Prisma.ContributorContributionWhereUniqueInput[]
  disconnect?: Prisma.ContributorContributionWhereUniqueInput | Prisma.ContributorContributionWhereUniqueInput[]
  delete?: Prisma.ContributorContributionWhereUniqueInput | Prisma.ContributorContributionWhereUniqueInput[]
  connect?: Prisma.ContributorContributionWhereUniqueInput | Prisma.ContributorContributionWhereUniqueInput[]
  update?: Prisma.ContributorContributionUpdateWithWhereUniqueWithoutRepositoryInput | Prisma.ContributorContributionUpdateWithWhereUniqueWithoutRepositoryInput[]
  updateMany?: Prisma.ContributorContributionUpdateManyWithWhereWithoutRepositoryInput | Prisma.ContributorContributionUpdateManyWithWhereWithoutRepositoryInput[]
  deleteMany?: Prisma.ContributorContributionScalarWhereInput | Prisma.ContributorContributionScalarWhereInput[]
}

export type ContributorContributionCreateNestedManyWithoutContributorInput = {
  create?: Prisma.XOR<Prisma.ContributorContributionCreateWithoutContributorInput, Prisma.ContributorContributionUncheckedCreateWithoutContributorInput> | Prisma.ContributorContributionCreateWithoutContributorInput[] | Prisma.ContributorContributionUncheckedCreateWithoutContributorInput[]
  connectOrCreate?: Prisma.ContributorContributionCreateOrConnectWithoutContributorInput | Prisma.ContributorContributionCreateOrConnectWithoutContributorInput[]
  createMany?: Prisma.ContributorContributionCreateManyContributorInputEnvelope
  connect?: Prisma.ContributorContributionWhereUniqueInput | Prisma.ContributorContributionWhereUniqueInput[]
}

export type ContributorContributionUncheckedCreateNestedManyWithoutContributorInput = {
  create?: Prisma.XOR<Prisma.ContributorContributionCreateWithoutContributorInput, Prisma.ContributorContributionUncheckedCreateWithoutContributorInput> | Prisma.ContributorContributionCreateWithoutContributorInput[] | Prisma.ContributorContributionUncheckedCreateWithoutContributorInput[]
  connectOrCreate?: Prisma.ContributorContributionCreateOrConnectWithoutContributorInput | Prisma.ContributorContributionCreateOrConnectWithoutContributorInput[]
  createMany?: Prisma.ContributorContributionCreateManyContributorInputEnvelope
  connect?: Prisma.ContributorContributionWhereUniqueInput | Prisma.ContributorContributionWhereUniqueInput[]
}

export type ContributorContributionUpdateManyWithoutContributorNestedInput = {
  create?: Prisma.XOR<Prisma.ContributorContributionCreateWithoutContributorInput, Prisma.ContributorContributionUncheckedCreateWithoutContributorInput> | Prisma.ContributorContributionCreateWithoutContributorInput[] | Prisma.ContributorContributionUncheckedCreateWithoutContributorInput[]
  connectOrCreate?: Prisma.ContributorContributionCreateOrConnectWithoutContributorInput | Prisma.ContributorContributionCreateOrConnectWithoutContributorInput[]
  upsert?: Prisma.ContributorContributionUpsertWithWhereUniqueWithoutContributorInput | Prisma.ContributorContributionUpsertWithWhereUniqueWithoutContributorInput[]
  createMany?: Prisma.ContributorContributionCreateManyContributorInputEnvelope
  set?: Prisma.ContributorContributionWhereUniqueInput | Prisma.ContributorContributionWhereUniqueInput[]
  disconnect?: Prisma.ContributorContributionWhereUniqueInput | Prisma.ContributorContributionWhereUniqueInput[]
  delete?: Prisma.ContributorContributionWhereUniqueInput | Prisma.ContributorContributionWhereUniqueInput[]
  connect?: Prisma.ContributorContributionWhereUniqueInput | Prisma.ContributorContributionWhereUniqueInput[]
  update?: Prisma.ContributorContributionUpdateWithWhereUniqueWithoutContributorInput | Prisma.ContributorContributionUpdateWithWhereUniqueWithoutContributorInput[]
  updateMany?: Prisma.ContributorContributionUpdateManyWithWhereWithoutContributorInput | Prisma.ContributorContributionUpdateManyWithWhereWithoutContributorInput[]
  deleteMany?: Prisma.ContributorContributionScalarWhereInput | Prisma.ContributorContributionScalarWhereInput[]
}

export type ContributorContributionUncheckedUpdateManyWithoutContributorNestedInput = {
  create?: Prisma.XOR<Prisma.ContributorContributionCreateWithoutContributorInput, Prisma.ContributorContributionUncheckedCreateWithoutContributorInput> | Prisma.ContributorContributionCreateWithoutContributorInput[] | Prisma.ContributorContributionUncheckedCreateWithoutContributorInput[]
  connectOrCreate?: Prisma.ContributorContributionCreateOrConnectWithoutContributorInput | Prisma.ContributorContributionCreateOrConnectWithoutContributorInput[]
  upsert?: Prisma.ContributorContributionUpsertWithWhereUniqueWithoutContributorInput | Prisma.ContributorContributionUpsertWithWhereUniqueWithoutContributorInput[]
  createMany?: Prisma.ContributorContributionCreateManyContributorInputEnvelope
  set?: Prisma.ContributorContributionWhereUniqueInput | Prisma.ContributorContributionWhereUniqueInput[]
  disconnect?: Prisma.ContributorContributionWhereUniqueInput | Prisma.ContributorContributionWhereUniqueInput[]
  delete?: Prisma.ContributorContributionWhereUniqueInput | Prisma.ContributorContributionWhereUniqueInput[]
  connect?: Prisma.ContributorContributionWhereUniqueInput | Prisma.ContributorContributionWhereUniqueInput[]
  update?: Prisma.ContributorContributionUpdateWithWhereUniqueWithoutContributorInput | Prisma.ContributorContributionUpdateWithWhereUniqueWithoutContributorInput[]
  updateMany?: Prisma.ContributorContributionUpdateManyWithWhereWithoutContributorInput | Prisma.ContributorContributionUpdateManyWithWhereWithoutContributorInput[]
  deleteMany?: Prisma.ContributorContributionScalarWhereInput | Prisma.ContributorContributionScalarWhereInput[]
}

export type ContributorContributionCreateWithoutRepositoryInput = {
  contributionsCount?: number
  syncedAt?: Date | string
  contributor: Prisma.ContributorCreateNestedOneWithoutContributionsInput
}

export type ContributorContributionUncheckedCreateWithoutRepositoryInput = {
  contributorId: string
  contributionsCount?: number
  syncedAt?: Date | string
}

export type ContributorContributionCreateOrConnectWithoutRepositoryInput = {
  where: Prisma.ContributorContributionWhereUniqueInput
  create: Prisma.XOR<Prisma.ContributorContributionCreateWithoutRepositoryInput, Prisma.ContributorContributionUncheckedCreateWithoutRepositoryInput>
}

export type ContributorContributionCreateManyRepositoryInputEnvelope = {
  data: Prisma.ContributorContributionCreateManyRepositoryInput | Prisma.ContributorContributionCreateManyRepositoryInput[]
  skipDuplicates?: boolean
}

export type ContributorContributionUpsertWithWhereUniqueWithoutRepositoryInput = {
  where: Prisma.ContributorContributionWhereUniqueInput
  update: Prisma.XOR<Prisma.ContributorContributionUpdateWithoutRepositoryInput, Prisma.ContributorContributionUncheckedUpdateWithoutRepositoryInput>
  create: Prisma.XOR<Prisma.ContributorContributionCreateWithoutRepositoryInput, Prisma.ContributorContributionUncheckedCreateWithoutRepositoryInput>
}

export type ContributorContributionUpdateWithWhereUniqueWithoutRepositoryInput = {
  where: Prisma.ContributorContributionWhereUniqueInput
  data: Prisma.XOR<Prisma.ContributorContributionUpdateWithoutRepositoryInput, Prisma.ContributorContributionUncheckedUpdateWithoutRepositoryInput>
}

export type ContributorContributionUpdateManyWithWhereWithoutRepositoryInput = {
  where: Prisma.ContributorContributionScalarWhereInput
  data: Prisma.XOR<Prisma.ContributorContributionUpdateManyMutationInput, Prisma.ContributorContributionUncheckedUpdateManyWithoutRepositoryInput>
}

export type ContributorContributionScalarWhereInput = {
  AND?: Prisma.ContributorContributionScalarWhereInput | Prisma.ContributorContributionScalarWhereInput[]
  OR?: Prisma.ContributorContributionScalarWhereInput[]
  NOT?: Prisma.ContributorContributionScalarWhereInput | Prisma.ContributorContributionScalarWhereInput[]
  contributorId?: Prisma.StringFilter<"ContributorContribution"> | string
  repositoryId?: Prisma.StringFilter<"ContributorContribution"> | string
  contributionsCount?: Prisma.IntFilter<"ContributorContribution"> | number
  syncedAt?: Prisma.DateTimeFilter<"ContributorContribution"> | Date | string
}

export type ContributorContributionCreateWithoutContributorInput = {
  contributionsCount?: number
  syncedAt?: Date | string
  repository: Prisma.RepositoryCreateNestedOneWithoutContributionsInput
}

export type ContributorContributionUncheckedCreateWithoutContributorInput = {
  repositoryId: string
  contributionsCount?: number
  syncedAt?: Date | string
}

export type ContributorContributionCreateOrConnectWithoutContributorInput = {
  where: Prisma.ContributorContributionWhereUniqueInput
  create: Prisma.XOR<Prisma.ContributorContributionCreateWithoutContributorInput, Prisma.ContributorContributionUncheckedCreateWithoutContributorInput>
}

export type ContributorContributionCreateManyContributorInputEnvelope = {
  data: Prisma.ContributorContributionCreateManyContributorInput | Prisma.ContributorContributionCreateManyContributorInput[]
  skipDuplicates?: boolean
}

export type ContributorContributionUpsertWithWhereUniqueWithoutContributorInput = {
  where: Prisma.ContributorContributionWhereUniqueInput
  update: Prisma.XOR<Prisma.ContributorContributionUpdateWithoutContributorInput, Prisma.ContributorContributionUncheckedUpdateWithoutContributorInput>
  create: Prisma.XOR<Prisma.ContributorContributionCreateWithoutContributorInput, Prisma.ContributorContributionUncheckedCreateWithoutContributorInput>
}

export type ContributorContributionUpdateWithWhereUniqueWithoutContributorInput = {
  where: Prisma.ContributorContributionWhereUniqueInput
  data: Prisma.XOR<Prisma.ContributorContributionUpdateWithoutContributorInput, Prisma.ContributorContributionUncheckedUpdateWithoutContributorInput>
}

export type ContributorContributionUpdateManyWithWhereWithoutContributorInput = {
  where: Prisma.ContributorContributionScalarWhereInput
  data: Prisma.XOR<Prisma.ContributorContributionUpdateManyMutationInput, Prisma.ContributorContributionUncheckedUpdateManyWithoutContributorInput>
}

export type ContributorContributionCreateManyRepositoryInput = {
  contributorId: string
  contributionsCount?: number
  syncedAt?: Date | string
}

export type ContributorContributionUpdateWithoutRepositoryInput = {
  contributionsCount?: Prisma.IntFieldUpdateOperationsInput | number
  syncedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  contributor?: Prisma.ContributorUpdateOneRequiredWithoutContributionsNestedInput
}

export type ContributorContributionUncheckedUpdateWithoutRepositoryInput = {
  contributorId?: Prisma.StringFieldUpdateOperationsInput | string
  contributionsCount?: Prisma.IntFieldUpdateOperationsInput | number
  syncedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type ContributorContributionUncheckedUpdateManyWithoutRepositoryInput = {
  contributorId?: Prisma.StringFieldUpdateOperationsInput | string
  contributionsCount?: Prisma.IntFieldUpdateOperationsInput | number
  syncedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type ContributorContributionCreateManyContributorInput = {
  repositoryId: string
  contributionsCount?: number
  syncedAt?: Date | string
}

export type ContributorContributionUpdateWithoutContributorInput = {
  contributionsCount?: Prisma.IntFieldUpdateOperationsInput | number
  syncedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  repository?: Prisma.RepositoryUpdateOneRequiredWithoutContributionsNestedInput
}

export type ContributorContributionUncheckedUpdateWithoutContributorInput = {
  repositoryId?: Prisma.StringFieldUpdateOperationsInput | string
  contributionsCount?: Prisma.IntFieldUpdateOperationsInput | number
  syncedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type ContributorContributionUncheckedUpdateManyWithoutContributorInput = {
  repositoryId?: Prisma.StringFieldUpdateOperationsInput | string
  contributionsCount?: Prisma.IntFieldUpdateOperationsInput | number
  syncedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}



export type ContributorContributionSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  contributorId?: boolean
  repositoryId?: boolean
  contributionsCount?: boolean
  syncedAt?: boolean
  contributor?: boolean | Prisma.ContributorDefaultArgs<ExtArgs>
  repository?: boolean | Prisma.RepositoryDefaultArgs<ExtArgs>
}, ExtArgs["result"]["contributorContribution"]>

export type ContributorContributionSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  contributorId?: boolean
  repositoryId?: boolean
  contributionsCount?: boolean
  syncedAt?: boolean
  contributor?: boolean | Prisma.ContributorDefaultArgs<ExtArgs>
  repository?: boolean | Prisma.RepositoryDefaultArgs<ExtArgs>
}, ExtArgs["result"]["contributorContribution"]>

export type ContributorContributionSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  contributorId?: boolean
  repositoryId?: boolean
  contributionsCount?: boolean
  syncedAt?: boolean
  contributor?: boolean | Prisma.ContributorDefaultArgs<ExtArgs>
  repository?: boolean | Prisma.RepositoryDefaultArgs<ExtArgs>
}, ExtArgs["result"]["contributorContribution"]>

export type ContributorContributionSelectScalar = {
  contributorId?: boolean
  repositoryId?: boolean
  contributionsCount?: boolean
  syncedAt?: boolean
}

export type ContributorContributionOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"contributorId" | "repositoryId" | "contributionsCount" | "syncedAt", ExtArgs["result"]["contributorContribution"]>
export type ContributorContributionInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  contributor?: boolean | Prisma.ContributorDefaultArgs<ExtArgs>
  repository?: boolean | Prisma.RepositoryDefaultArgs<ExtArgs>
}
export type ContributorContributionIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  contributor?: boolean | Prisma.ContributorDefaultArgs<ExtArgs>
  repository?: boolean | Prisma.RepositoryDefaultArgs<ExtArgs>
}
export type ContributorContributionIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  contributor?: boolean | Prisma.ContributorDefaultArgs<ExtArgs>
  repository?: boolean | Prisma.RepositoryDefaultArgs<ExtArgs>
}

export type $ContributorContributionPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "ContributorContribution"
  objects: {
    contributor: Prisma.$ContributorPayload<ExtArgs>
    repository: Prisma.$RepositoryPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    contributorId: string
    repositoryId: string
    contributionsCount: number
    syncedAt: Date
  }, ExtArgs["result"]["contributorContribution"]>
  composites: {}
}

export type ContributorContributionGetPayload<S extends boolean | null | undefined | ContributorContributionDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$ContributorContributionPayload, S>

export type ContributorContributionCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<ContributorContributionFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: ContributorContributionCountAggregateInputType | true
  }

export interface ContributorContributionDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['ContributorContribution'], meta: { name: 'ContributorContribution' } }
  /**
   * Find zero or one ContributorContribution that matches the filter.
   * @param {ContributorContributionFindUniqueArgs} args - Arguments to find a ContributorContribution
   * @example
   * // Get one ContributorContribution
   * const contributorContribution = await prisma.contributorContribution.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends ContributorContributionFindUniqueArgs>(args: Prisma.SelectSubset<T, ContributorContributionFindUniqueArgs<ExtArgs>>): Prisma.Prisma__ContributorContributionClient<runtime.Types.Result.GetResult<Prisma.$ContributorContributionPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one ContributorContribution that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {ContributorContributionFindUniqueOrThrowArgs} args - Arguments to find a ContributorContribution
   * @example
   * // Get one ContributorContribution
   * const contributorContribution = await prisma.contributorContribution.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends ContributorContributionFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, ContributorContributionFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__ContributorContributionClient<runtime.Types.Result.GetResult<Prisma.$ContributorContributionPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first ContributorContribution that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ContributorContributionFindFirstArgs} args - Arguments to find a ContributorContribution
   * @example
   * // Get one ContributorContribution
   * const contributorContribution = await prisma.contributorContribution.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends ContributorContributionFindFirstArgs>(args?: Prisma.SelectSubset<T, ContributorContributionFindFirstArgs<ExtArgs>>): Prisma.Prisma__ContributorContributionClient<runtime.Types.Result.GetResult<Prisma.$ContributorContributionPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first ContributorContribution that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ContributorContributionFindFirstOrThrowArgs} args - Arguments to find a ContributorContribution
   * @example
   * // Get one ContributorContribution
   * const contributorContribution = await prisma.contributorContribution.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends ContributorContributionFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, ContributorContributionFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__ContributorContributionClient<runtime.Types.Result.GetResult<Prisma.$ContributorContributionPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more ContributorContributions that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ContributorContributionFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all ContributorContributions
   * const contributorContributions = await prisma.contributorContribution.findMany()
   * 
   * // Get first 10 ContributorContributions
   * const contributorContributions = await prisma.contributorContribution.findMany({ take: 10 })
   * 
   * // Only select the `contributorId`
   * const contributorContributionWithContributorIdOnly = await prisma.contributorContribution.findMany({ select: { contributorId: true } })
   * 
   */
  findMany<T extends ContributorContributionFindManyArgs>(args?: Prisma.SelectSubset<T, ContributorContributionFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ContributorContributionPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a ContributorContribution.
   * @param {ContributorContributionCreateArgs} args - Arguments to create a ContributorContribution.
   * @example
   * // Create one ContributorContribution
   * const ContributorContribution = await prisma.contributorContribution.create({
   *   data: {
   *     // ... data to create a ContributorContribution
   *   }
   * })
   * 
   */
  create<T extends ContributorContributionCreateArgs>(args: Prisma.SelectSubset<T, ContributorContributionCreateArgs<ExtArgs>>): Prisma.Prisma__ContributorContributionClient<runtime.Types.Result.GetResult<Prisma.$ContributorContributionPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many ContributorContributions.
   * @param {ContributorContributionCreateManyArgs} args - Arguments to create many ContributorContributions.
   * @example
   * // Create many ContributorContributions
   * const contributorContribution = await prisma.contributorContribution.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends ContributorContributionCreateManyArgs>(args?: Prisma.SelectSubset<T, ContributorContributionCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many ContributorContributions and returns the data saved in the database.
   * @param {ContributorContributionCreateManyAndReturnArgs} args - Arguments to create many ContributorContributions.
   * @example
   * // Create many ContributorContributions
   * const contributorContribution = await prisma.contributorContribution.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many ContributorContributions and only return the `contributorId`
   * const contributorContributionWithContributorIdOnly = await prisma.contributorContribution.createManyAndReturn({
   *   select: { contributorId: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends ContributorContributionCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, ContributorContributionCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ContributorContributionPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a ContributorContribution.
   * @param {ContributorContributionDeleteArgs} args - Arguments to delete one ContributorContribution.
   * @example
   * // Delete one ContributorContribution
   * const ContributorContribution = await prisma.contributorContribution.delete({
   *   where: {
   *     // ... filter to delete one ContributorContribution
   *   }
   * })
   * 
   */
  delete<T extends ContributorContributionDeleteArgs>(args: Prisma.SelectSubset<T, ContributorContributionDeleteArgs<ExtArgs>>): Prisma.Prisma__ContributorContributionClient<runtime.Types.Result.GetResult<Prisma.$ContributorContributionPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one ContributorContribution.
   * @param {ContributorContributionUpdateArgs} args - Arguments to update one ContributorContribution.
   * @example
   * // Update one ContributorContribution
   * const contributorContribution = await prisma.contributorContribution.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends ContributorContributionUpdateArgs>(args: Prisma.SelectSubset<T, ContributorContributionUpdateArgs<ExtArgs>>): Prisma.Prisma__ContributorContributionClient<runtime.Types.Result.GetResult<Prisma.$ContributorContributionPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more ContributorContributions.
   * @param {ContributorContributionDeleteManyArgs} args - Arguments to filter ContributorContributions to delete.
   * @example
   * // Delete a few ContributorContributions
   * const { count } = await prisma.contributorContribution.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends ContributorContributionDeleteManyArgs>(args?: Prisma.SelectSubset<T, ContributorContributionDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more ContributorContributions.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ContributorContributionUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many ContributorContributions
   * const contributorContribution = await prisma.contributorContribution.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends ContributorContributionUpdateManyArgs>(args: Prisma.SelectSubset<T, ContributorContributionUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more ContributorContributions and returns the data updated in the database.
   * @param {ContributorContributionUpdateManyAndReturnArgs} args - Arguments to update many ContributorContributions.
   * @example
   * // Update many ContributorContributions
   * const contributorContribution = await prisma.contributorContribution.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more ContributorContributions and only return the `contributorId`
   * const contributorContributionWithContributorIdOnly = await prisma.contributorContribution.updateManyAndReturn({
   *   select: { contributorId: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends ContributorContributionUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, ContributorContributionUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ContributorContributionPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one ContributorContribution.
   * @param {ContributorContributionUpsertArgs} args - Arguments to update or create a ContributorContribution.
   * @example
   * // Update or create a ContributorContribution
   * const contributorContribution = await prisma.contributorContribution.upsert({
   *   create: {
   *     // ... data to create a ContributorContribution
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the ContributorContribution we want to update
   *   }
   * })
   */
  upsert<T extends ContributorContributionUpsertArgs>(args: Prisma.SelectSubset<T, ContributorContributionUpsertArgs<ExtArgs>>): Prisma.Prisma__ContributorContributionClient<runtime.Types.Result.GetResult<Prisma.$ContributorContributionPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of ContributorContributions.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ContributorContributionCountArgs} args - Arguments to filter ContributorContributions to count.
   * @example
   * // Count the number of ContributorContributions
   * const count = await prisma.contributorContribution.count({
   *   where: {
   *     // ... the filter for the ContributorContributions we want to count
   *   }
   * })
  **/
  count<T extends ContributorContributionCountArgs>(
    args?: Prisma.Subset<T, ContributorContributionCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], ContributorContributionCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a ContributorContribution.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ContributorContributionAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends ContributorContributionAggregateArgs>(args: Prisma.Subset<T, ContributorContributionAggregateArgs>): Prisma.PrismaPromise<GetContributorContributionAggregateType<T>>

  /**
   * Group by ContributorContribution.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ContributorContributionGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends ContributorContributionGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: ContributorContributionGroupByArgs['orderBy'] }
      : { orderBy?: ContributorContributionGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, ContributorContributionGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetContributorContributionGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the ContributorContribution model
 */
readonly fields: ContributorContributionFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for ContributorContribution.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__ContributorContributionClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  contributor<T extends Prisma.ContributorDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.ContributorDefaultArgs<ExtArgs>>): Prisma.Prisma__ContributorClient<runtime.Types.Result.GetResult<Prisma.$ContributorPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  repository<T extends Prisma.RepositoryDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.RepositoryDefaultArgs<ExtArgs>>): Prisma.Prisma__RepositoryClient<runtime.Types.Result.GetResult<Prisma.$RepositoryPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the ContributorContribution model
 */
export interface ContributorContributionFieldRefs {
  readonly contributorId: Prisma.FieldRef<"ContributorContribution", 'String'>
  readonly repositoryId: Prisma.FieldRef<"ContributorContribution", 'String'>
  readonly contributionsCount: Prisma.FieldRef<"ContributorContribution", 'Int'>
  readonly syncedAt: Prisma.FieldRef<"ContributorContribution", 'DateTime'>
}
    

// Custom InputTypes
/**
 * ContributorContribution findUnique
 */
export type ContributorContributionFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ContributorContribution
   */
  select?: Prisma.ContributorContributionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ContributorContribution
   */
  omit?: Prisma.ContributorContributionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ContributorContributionInclude<ExtArgs> | null
  /**
   * Filter, which ContributorContribution to fetch.
   */
  where: Prisma.ContributorContributionWhereUniqueInput
}

/**
 * ContributorContribution findUniqueOrThrow
 */
export type ContributorContributionFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ContributorContribution
   */
  select?: Prisma.ContributorContributionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ContributorContribution
   */
  omit?: Prisma.ContributorContributionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ContributorContributionInclude<ExtArgs> | null
  /**
   * Filter, which ContributorContribution to fetch.
   */
  where: Prisma.ContributorContributionWhereUniqueInput
}

/**
 * ContributorContribution findFirst
 */
export type ContributorContributionFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ContributorContribution
   */
  select?: Prisma.ContributorContributionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ContributorContribution
   */
  omit?: Prisma.ContributorContributionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ContributorContributionInclude<ExtArgs> | null
  /**
   * Filter, which ContributorContribution to fetch.
   */
  where?: Prisma.ContributorContributionWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ContributorContributions to fetch.
   */
  orderBy?: Prisma.ContributorContributionOrderByWithRelationInput | Prisma.ContributorContributionOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for ContributorContributions.
   */
  cursor?: Prisma.ContributorContributionWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ContributorContributions from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ContributorContributions.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of ContributorContributions.
   */
  distinct?: Prisma.ContributorContributionScalarFieldEnum | Prisma.ContributorContributionScalarFieldEnum[]
}

/**
 * ContributorContribution findFirstOrThrow
 */
export type ContributorContributionFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ContributorContribution
   */
  select?: Prisma.ContributorContributionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ContributorContribution
   */
  omit?: Prisma.ContributorContributionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ContributorContributionInclude<ExtArgs> | null
  /**
   * Filter, which ContributorContribution to fetch.
   */
  where?: Prisma.ContributorContributionWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ContributorContributions to fetch.
   */
  orderBy?: Prisma.ContributorContributionOrderByWithRelationInput | Prisma.ContributorContributionOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for ContributorContributions.
   */
  cursor?: Prisma.ContributorContributionWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ContributorContributions from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ContributorContributions.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of ContributorContributions.
   */
  distinct?: Prisma.ContributorContributionScalarFieldEnum | Prisma.ContributorContributionScalarFieldEnum[]
}

/**
 * ContributorContribution findMany
 */
export type ContributorContributionFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ContributorContribution
   */
  select?: Prisma.ContributorContributionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ContributorContribution
   */
  omit?: Prisma.ContributorContributionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ContributorContributionInclude<ExtArgs> | null
  /**
   * Filter, which ContributorContributions to fetch.
   */
  where?: Prisma.ContributorContributionWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ContributorContributions to fetch.
   */
  orderBy?: Prisma.ContributorContributionOrderByWithRelationInput | Prisma.ContributorContributionOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing ContributorContributions.
   */
  cursor?: Prisma.ContributorContributionWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ContributorContributions from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ContributorContributions.
   */
  skip?: number
  distinct?: Prisma.ContributorContributionScalarFieldEnum | Prisma.ContributorContributionScalarFieldEnum[]
}

/**
 * ContributorContribution create
 */
export type ContributorContributionCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ContributorContribution
   */
  select?: Prisma.ContributorContributionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ContributorContribution
   */
  omit?: Prisma.ContributorContributionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ContributorContributionInclude<ExtArgs> | null
  /**
   * The data needed to create a ContributorContribution.
   */
  data: Prisma.XOR<Prisma.ContributorContributionCreateInput, Prisma.ContributorContributionUncheckedCreateInput>
}

/**
 * ContributorContribution createMany
 */
export type ContributorContributionCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many ContributorContributions.
   */
  data: Prisma.ContributorContributionCreateManyInput | Prisma.ContributorContributionCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * ContributorContribution createManyAndReturn
 */
export type ContributorContributionCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ContributorContribution
   */
  select?: Prisma.ContributorContributionSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the ContributorContribution
   */
  omit?: Prisma.ContributorContributionOmit<ExtArgs> | null
  /**
   * The data used to create many ContributorContributions.
   */
  data: Prisma.ContributorContributionCreateManyInput | Prisma.ContributorContributionCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ContributorContributionIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * ContributorContribution update
 */
export type ContributorContributionUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ContributorContribution
   */
  select?: Prisma.ContributorContributionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ContributorContribution
   */
  omit?: Prisma.ContributorContributionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ContributorContributionInclude<ExtArgs> | null
  /**
   * The data needed to update a ContributorContribution.
   */
  data: Prisma.XOR<Prisma.ContributorContributionUpdateInput, Prisma.ContributorContributionUncheckedUpdateInput>
  /**
   * Choose, which ContributorContribution to update.
   */
  where: Prisma.ContributorContributionWhereUniqueInput
}

/**
 * ContributorContribution updateMany
 */
export type ContributorContributionUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update ContributorContributions.
   */
  data: Prisma.XOR<Prisma.ContributorContributionUpdateManyMutationInput, Prisma.ContributorContributionUncheckedUpdateManyInput>
  /**
   * Filter which ContributorContributions to update
   */
  where?: Prisma.ContributorContributionWhereInput
  /**
   * Limit how many ContributorContributions to update.
   */
  limit?: number
}

/**
 * ContributorContribution updateManyAndReturn
 */
export type ContributorContributionUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ContributorContribution
   */
  select?: Prisma.ContributorContributionSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the ContributorContribution
   */
  omit?: Prisma.ContributorContributionOmit<ExtArgs> | null
  /**
   * The data used to update ContributorContributions.
   */
  data: Prisma.XOR<Prisma.ContributorContributionUpdateManyMutationInput, Prisma.ContributorContributionUncheckedUpdateManyInput>
  /**
   * Filter which ContributorContributions to update
   */
  where?: Prisma.ContributorContributionWhereInput
  /**
   * Limit how many ContributorContributions to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ContributorContributionIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * ContributorContribution upsert
 */
export type ContributorContributionUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ContributorContribution
   */
  select?: Prisma.ContributorContributionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ContributorContribution
   */
  omit?: Prisma.ContributorContributionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ContributorContributionInclude<ExtArgs> | null
  /**
   * The filter to search for the ContributorContribution to update in case it exists.
   */
  where: Prisma.ContributorContributionWhereUniqueInput
  /**
   * In case the ContributorContribution found by the `where` argument doesn't exist, create a new ContributorContribution with this data.
   */
  create: Prisma.XOR<Prisma.ContributorContributionCreateInput, Prisma.ContributorContributionUncheckedCreateInput>
  /**
   * In case the ContributorContribution was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.ContributorContributionUpdateInput, Prisma.ContributorContributionUncheckedUpdateInput>
}

/**
 * ContributorContribution delete
 */
export type ContributorContributionDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ContributorContribution
   */
  select?: Prisma.ContributorContributionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ContributorContribution
   */
  omit?: Prisma.ContributorContributionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ContributorContributionInclude<ExtArgs> | null
  /**
   * Filter which ContributorContribution to delete.
   */
  where: Prisma.ContributorContributionWhereUniqueInput
}

/**
 * ContributorContribution deleteMany
 */
export type ContributorContributionDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which ContributorContributions to delete
   */
  where?: Prisma.ContributorContributionWhereInput
  /**
   * Limit how many ContributorContributions to delete.
   */
  limit?: number
}

/**
 * ContributorContribution without action
 */
export type ContributorContributionDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ContributorContribution
   */
  select?: Prisma.ContributorContributionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ContributorContribution
   */
  omit?: Prisma.ContributorContributionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ContributorContributionInclude<ExtArgs> | null
}
