
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file should be your main import to use Prisma-related types and utilities in a browser. 
 * Use it to get access to models, enums, and input types.
 * 
 * This file does not contain a `PrismaClient` class, nor several other helpers that are intended as server-side only.
 * See `client.ts` for the standard, server-side entry point.
 *
 * 🟢 You can import this file directly.
 */

import * as Prisma from './internal/prismaNamespaceBrowser'
export { Prisma }
export * as $Enums from './enums'
export * from './enums';
/**
 * Model Repository
 * 
 */
export type Repository = Prisma.RepositoryModel
/**
 * Model Issue
 * 
 */
export type Issue = Prisma.IssueModel
/**
 * Model PullRequest
 * 
 */
export type PullRequest = Prisma.PullRequestModel
/**
 * Model Commit
 * 
 */
export type Commit = Prisma.CommitModel
/**
 * Model Release
 * 
 */
export type Release = Prisma.ReleaseModel
/**
 * Model VersionTag
 * 
 */
export type VersionTag = Prisma.VersionTagModel
/**
 * Model Contributor
 * 
 */
export type Contributor = Prisma.ContributorModel
/**
 * Model ContributorContribution
 * 
 */
export type ContributorContribution = Prisma.ContributorContributionModel
/**
 * Model DocumentationContent
 * 
 */
export type DocumentationContent = Prisma.DocumentationContentModel
/**
 * Model DocumentationMetadata
 * 
 */
export type DocumentationMetadata = Prisma.DocumentationMetadataModel
/**
 * Model SyncLog
 * 
 */
export type SyncLog = Prisma.SyncLogModel
/**
 * Model Settings
 * 
 */
export type Settings = Prisma.SettingsModel
/**
 * Model Project
 * 
 */
export type Project = Prisma.ProjectModel
/**
 * Model ProjectSource
 * 
 */
export type ProjectSource = Prisma.ProjectSourceModel
/**
 * Model Version
 * 
 */
export type Version = Prisma.VersionModel
/**
 * Model Content
 * 
 */
export type Content = Prisma.ContentModel
/**
 * Model NavStructure
 * 
 */
export type NavStructure = Prisma.NavStructureModel
