
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
* This file exports all enum related types from the schema.
*
* 🟢 You can import this file directly.
*/

export const IssueState = {
  open: 'open',
  closed: 'closed'
} as const

export type IssueState = (typeof IssueState)[keyof typeof IssueState]


export const PrState = {
  open: 'open',
  closed: 'closed',
  merged: 'merged'
} as const

export type PrState = (typeof PrState)[keyof typeof PrState]


export const SyncStatus = {
  pending: 'pending',
  in_progress: 'in_progress',
  completed: 'completed',
  failed: 'failed'
} as const

export type SyncStatus = (typeof SyncStatus)[keyof typeof SyncStatus]
