[build]
  command = "pnpm turbo run build --filter=hub"
  publish = "apps/hub/.next"
  ignore = "test -z \"$(git diff --name-only $CACHED_COMMIT_REF $COMMIT_REF -- apps/hub)\" && test -n \"$(git diff --name-only $CACHED_COMMIT_REF $COMMIT_REF -- apps/www apps/docs)\""

[[plugins]]
  package = "@netlify/plugin-nextjs"

[build.environment]
  NODE_VERSION = "22"
  NPM_FLAGS = "--legacy-peer-deps"
  SECRETS_SCAN_OMIT_PATHS = "apps/www,apps/docs"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[context.production]
  command = "pnpm turbo run build --filter=hub"

[context.deploy-preview]
  command = "pnpm turbo run build --filter=hub"

[context.branch-deploy]
  command = "pnpm turbo run build --filter=hub"


# Required environment variables (set in Netlify UI):
# HUB_API_KEY
# NEXT_PUBLIC_BASE_URL
# DATABASE_URL
# NEXT_PUBLIC_CLERK_SIGN_IN_URL
# NEXT_PUBLIC_CLERK_SIGN_IN_FALLBACK_REDIRECT_URL
# NEXT_PUBLIC_CLERK_SIGN_UP_FALLBACK_REDIRECT_URL
# NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY
# GITHUB_TOKEN
# GITHUB_WEBHOOK_SECRET

